### ISSUE TITLE
CSP is blocking page loading

### ISSUE THREAD

**Issue by abishai** [nextcloud/ocsms#119]
I installed ocsms app in nextcloud-9.0.53
I have problems when I opening SMS page from nextcloud menu (it should be empty as no attempt to sync was done) - the loading animation plays and that's all.

In console I see 
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://my domain 'unsafe-eval'").

I curl'd to server and fetched the following policy:
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src \* data: blob:; font-src 'self' data:; media-src *; connect-src *

I have not usual config (see server below), however other apps works.
config.php has additional settings
  'overwriteprotocol' => 'https',
  'overwritehost' => 'my.domain',
### Server configuration

**ownCloud version:**  nextcloud-9.0.53

**PHP version:** php56

**HTTPd server:** nginx behind nginx doing https (reverse proxy)

**Comment by abishai** [comment]
Actually, maybe this is intended behaviour ? I see that CSP error is triggering in all pages, so maybe this is 'normal' (well ,I suppose it is not, but at least it's not breaking other apps). Network monitor sees activity, so I can't say scripts are broken.

**Comment by nerzhul** [comment]
hello @abishai cahnge you tell me which eval is unsafe ? because as i remember i didn't use this method. Ocsms is a pure angularJS app, it use REST methods, unrelated to domain named

**Comment by abishai** [comment]
Hello. 
Actually, I hit another issue with SMS App documented herel https://github.com/nerzhul/ownCloud-SMS-App So, I stopped debugging the link between application and phone. I'm waiting when updated version of the app will be pushed into F-Droid.

**Comment by nerzhul** [comment]
Please note i don't maintain the F-Droid repository, only the Google Play Store

**Comment by nerzhul** [comment]
The CSP issue is not existent anymore on this app
