### ISSUE TITLE
[Question] How to overwrite database?

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/ocsms#126]
How to overwrite database?
I don't know why, but smses from one contact (I saw only one contact with this problem, but can be more) contain only smses sent by me, but I can't see smses sent to me.

I would like to synchronise all smses again and maybe all smses will be stored this time.

**Comment by nerzhul** [comment]
@pawlosck what do you want to do with database exactly ?

**Comment by nerzhul** [comment]
just truncate oc_ocsms_sms_datas

**Comment by nerzhul** [comment]
on the store it's the raw data, the PHP code does the dedup if you select the country code
