### ISSUE TITLE
Support for Emoticons in messages

### ISSUE THREAD

**Issue by powerpaul17** [nextcloud/ocsms#154]
### Steps to reproduce
1. Tried to activate the app
2. Fails with error message (see below)

### Expected behaviour
Should install and activate the app

### Actual behaviour
Fails with error message (see below)

### Server configuration

**NextCloud/ownCloud version:** NC 11.0.0

**PHP version:** 7.0.8

**HTTPd server:** Apache2

**HTTPS:** Yes

### Client configuration

Latest version, but not relevant here.

### Logs
This is the error message I got when trying to activate the app. It is probably due to the enabled utf8mb4 collation setting of the MySQL server. In order to use emoticons throughout NC apps it would be very useful to support that. Also, phone text messages are very likely to contain a lot of emoticons.

```
An exception occurred while executing 'CREATE TABLE `oc_ocsms_smsdatas` (`id` BIGINT AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `added` DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, `lastmodified` DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, `sms_id` BIGINT NOT NULL, `sms_address` VARCHAR(64) NOT NULL, `sms_msg` VARCHAR(20480) NOT NULL, `sms_date` BIGINT NOT NULL, `sms_flags` VARCHAR(2) DEFAULT '00' NOT NULL, `sms_mailbox` SMALLINT NOT NULL, `sms_type` SMALLINT NOT NULL, INDEX smsdata_user_mailbox (`user_id`, `sms_mailbox`), INDEX smsdata_user_smsid (`user_id`, `sms_id`), INDEX smsdata_user_mailbox_date (`user_id`, `sms_mailbox`, `sms_date`), INDEX smsdata_user_mailbox_address (`user_id`, `sms_mailbox`, `sms_address`), INDEX smsdata_user_mailbox_address_date (`user_id`, `sms_mailbox`, `sms_address`, `sms_date`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'sms_msg' (max = 16383); use BLOB or TEXT instead
```

**Comment by powerpaul17** [comment]
It is related, but maybe I gave too little information, sorry for that.

[Here](https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html) it is described howto enable the multibyte configuration of the mysql database in order to support emoticons in all nextcloud apps. After doing that, the activation of the sms app fails with the above mentioned error message.

**Comment by nerzhul** [comment]
@powerpaul17 interesting doc but it's experimental feature, i'm only working on non experimental feature and also we need portable backend (sqlite + postgresql + mysql)

**Comment by powerpaul17** [comment]
In my opinion this is a absolutely necessary feature nowadays. But anyway, I was able to install and activate the app by changing the size of the "sms_msg" field to 10240. This should also be more than enough for a single message.

```
<field>
	<name>sms_msg</name>
	<type>text</type>
	<notnull>true</notnull>
	<length>10240</length>
</field>
```

**Comment by nerzhul** [comment]
It's fixed
