### ISSUE TITLE
[Question] Documentation of db fields?

### ISSUE THREAD

**Issue by FrederikLauber** [nextcloud/ocsms#155]
Hi,

could someone please provide me with the documentaion of teh database fields used by ocsms?

I still have some dumped sms information from my last phone and want to write a program to push these sms into the database of my ocsms. While I already figured out how the sms were stored in the first place, I still need to know what all the fields in ocsms mean.

Thanks in advance!

PS:
These are the fields in question:
id	bigint(20)
user_id	varchar(64)
added	datetime
lastmodified	datetime
sms_id	bigint(20)
sms_address	varchar(64)
sms_msg	varchar(20480)
sms_date	bigint(20)
sms_flags	varchar(2)
sms_mailbox	smallint(6) 
sms_type	smallint(6)

**Comment by nerzhul** [comment]
Hi @FrederikLauber it's quasi exactly Android database fieldsn except user_id, added and lastmodified

**Comment by FrederikLauber** [comment]
Hi,

can you at least tell me by what you are identifying messages which need to be synced from the phone?
Id + date?
If you are only be using id I guess, you would have problems due to resets on the phne, right?

**Comment by nerzhul** [comment]
at this moment id is used if i remember and we should switch to date

**Comment by FrederikLauber** [comment]
Hi,

also there seems to be something funny with the encoding...
As far as I understand, ocsms uses MySQL utf8_bin which only allows for 3 byte or less symbols and a lot of emojys are 4 byte long. Do you use soem kind of escaping?

**Comment by nerzhul** [comment]
@FrederikLauber we have problems with this, i didn't found a valid solution for this, if you know how can we fix this could be nice

**Comment by pci06** [comment]
I think you should try #165

**Comment by FrederikLauber** [comment]
Wow, Wow, Wow, hold on there.
Are you telling me that any sms encoded with 4byte utf8 (like an emoji) is not backuped by ocsms due to mysqls lack of proper utf8 support?

@pci06 sorry, that does not work in my case, my hoster is running cent os 6 and the mysql version is too old to be run with utf8mb4 and setting it to text seems to have the same problems.

Darn, I knew mysql was a nightmare, never new how deep this is going...
