### ISSUE TITLE
Sync old messages

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/ocsms#156]
Would love to be able to sync my old messages as a backup - perhaps it wouldn't be too hard for the app to slowly go through and back up/sync my old messages over time?

Running Nextcloud 11, Ubuntu, Nextcloud SMS 1.11.4

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**NextCloud/ownCloud version:**

**PHP version:**

**HTTPd server:**

**HTTPS:**

### Client configuration

**Android version:**

**Phone:**

**ownCloud SMS app version:**

### Logs

```
Insert your log here
```

**Comment by nerzhul** [comment]
Application synchronise messages differentially, what is the problem here ?

**Comment by adamlove86** [comment]
There is no problem, I got it working for the first time after the update.
The only thing is it only syncs new messages, and it would be great to have old messages, too. This makes the "restore all messages" function on the phone app so much more useful.
Thanks for your help and hope to hear from you soon!

**Comment by nerzhul** [comment]
@adamlove86 i see the problem now, our current sync model is incremental & differential, it records the last ack date for the next synchronization.

Do you think adding a button to reset the last synchronized date to 0, permitting next synchronization to do full differential sync is a good solution ?

**Comment by Magissia** [comment]
Yes

**Comment by adamlove86** [comment]
At the same time, I have approx 60,000 messages on my phone, so yes backup date from zero, but if backup doesn't complete at once, hopefully it can pick up from where it left off, or it can just synchronise a little more each time, in blocks of 500 or 1000, etc.

**Comment by nerzhul** [comment]
don't forget it not's really a backup for a synchronization. And the synchronization is already paginated to prevent memory usage on Android and server side

**Comment by nerzhul** [comment]
@adamlove86 can you re-open this issue in https://github.com/nerzhul/ownCloud-SMS-App please ?

**Comment by UkeFan** [comment]
I still can't sync old messages. Tapped both buttons many times, but in nextcloud only the new show up ));;
