### ISSUE TITLE
login or password incorrect

### ISSUE THREAD

**Issue by adri66** [nextcloud/ocsms#160]
I put the correct login and password but ownloud sms app make error "Login or password incorrect"

Sorry I don't have more information

Regards

**Comment by nerzhul** [comment]
do you have 2FA enabled ?

**Comment by adri66** [comment]
No, when I'm connect to nextcloud just enter my name and my password and it's work but on ocsm  I have the error "Login or password incorrect" 😕

**Comment by adri66** [comment]
I find the problem !
I use cloudFlare for manage my dns and It's seting to pass http proxy for acces to my nextcloud

I have disable de http proxy and it's work fine !

**Comment by nerzhul** [comment]
Nice, i close the issue
