### ISSUE TITLE
 Contact name sync

### ISSUE THREAD

**Issue by Myppomeu** [nextcloud/ocsms#161]
### Steps to reproduce
1. Sync sms with old app (ownCloud-SMS)
2. See web interface
3. Sync sms with new app (Nextcloud SMS)
4. See web interface

### Expected behaviour
Expected behaviour is to see contact name in conversation name

### Actual behaviour
Not every contact name syncs, I see just phone numbers

### Server configuration

**NextCloud version:**
11.0.1

**PHP version:**
5.6.29

**HTTPd server:**
nginx 1.6.2

**HTTPS:**
No.

### Client configuration

**Android version:**
Android 6, Cyanogenmod 13

**Phone:**
Xiaomi Redmi Note 3 Pro

**Nextcloud SMS app version:**
0.24.0

### Logs
What logs should I provide?

**Comment by nerzhul** [comment]
Sorry but contact names are not synced. Please use contact app in nextcloud to make them solvable

**Comment by Myppomeu** [comment]
Then how be explained that some contacts have names in SMS app? Contact app is installed.

**Comment by nerzhul** [comment]
Yes exactly, i didn't reinvent wheel, there is a very good contact sync using carddav, if you use it with oc sms everything will work properly

**Comment by Myppomeu** [comment]
I found the reason. If contact have different numbers in carddav and sms, name does not displayed. For example, in carddav:
89995552233
In sms:
+79995552233
In android such difference does not matter.
Can this be fixed in ocsms or I should write to contacts app issue tracker?

**Comment by nerzhul** [comment]
You should change your country in server side ocsms app to make numbers match

**Comment by Myppomeu** [comment]
Yes, this was already done (in user settings in ocsms app), but does not help.
