### ISSUE TITLE
"HTTP_RAW_POST_DATA is deprecated" in log

### ISSUE THREAD

**Issue by Myppomeu** [nextcloud/ocsms#162]
### Steps to reproduce
1. Install Nextcloud SMS in Nextcloud instance and phone
2. Sync SMS
3. See Nextcloud log

### Expected behaviour
No errors

### Actual behaviour
Errors in log

### Server configuration

**NextCloud version:**
11.0.1

**PHP version:**
5.6.29

**HTTPd server:**
nginx 1.6.2

**HTTPS:**
No.

### Client configuration

**Android version:**
Android 6, Cyanogenmod 13

**Phone:**
Xiaomi Redmi Note 3 Pro

**Nextcloud SMS app version:**
0.24.0

### Logs

```
Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0
```

**Comment by nerzhul** [comment]
hello
thanks for the report, but what is this ? in PHP 7.0.15 (future version then) i haven't this warning.

Also, i think it's an upstream issue, we are not doing this ourselved

**Comment by Myppomeu** [comment]
Ok. Sorry for disturbing.
