### ISSUE TITLE
[Feature request] Google PageSpeed Tools

### ISSUE THREAD

**Issue by aventrax** [nextcloud/ocsms#163]
Nextcloud scores only 20/100 with Google PageSpeed and there are many optimizations to be implemented (PageSpeed  show them). Is this kind of improvement scheduled for nextcloud?
I see my 2 installations are quite slow sometimes, especially from mobile...

https://developers.google.com/speed/pagespeed/

**Comment by nerzhul** [comment]
Not related with this app
