### ISSUE TITLE
Favicon: Adapt Nextcloud color theme

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/ocsms#164]
### Steps to reproduce
The favicon still has the oC dark blue, could this be changed to the Nc light blue?
This way it would fit nicely with the standard favicon and color theme.

![2017-01-23 17_31_42-sms - nextcloud](https://cloud.githubusercontent.com/assets/1315170/22212670/e1856ca8-e191-11e6-9a1d-d6977e242acd.png)

### Server configuration

**NextCloud/ownCloud version:**

* Nextcloud SMS 1.11.4
* Nextcloud 11.0.1

**Comment by nerzhul** [comment]
Yes it's possible without problem as nextcloud is our main support, and oc just a backport now
