### ISSUE TITLE
Activate translations on Transifex

### ISSUE THREAD

**Issue by enoch85** [nextcloud/ocsms#166]
Now when the app is under the /nextcloud repo on Github, wouldn't it be kind of easy to activate translation via Transifex?

**Comment by nerzhul** [comment]
@enoch85 could be possible but i'm not very transifex aware

**Comment by enoch85** [comment]
Maybe @MorrisJobke knows more?

**Comment by MorrisJobke** [comment]
> Now when the app is under the /nextcloud repo on Github, wouldn't it be kind of easy to activate translation via Transifex?

It's also easy if it's not within the nextcloud repo 😉 

Let me activate it.

**Comment by enoch85** [comment]
@MorrisJobke Great, thanks! 

Could you do the same for https://github.com/nerzhul/ownCloud-SMS-App/issues?

**Comment by MorrisJobke** [comment]
Done and works https://www.transifex.com/nextcloud/nextcloud/ocsms/

**Comment by MorrisJobke** [comment]
> Could you do the same for https://github.com/nerzhul/ownCloud-SMS-App/issues?

Please open a ticket over there.

**Comment by MorrisJobke** [comment]
> Please open a ticket over there.

Because for those repos @nextcloud-bot needs push access ;)

**Comment by enoch85** [comment]
@MorrisJobke Thanks a bunch!

@nerzhul Do you mind setting this up now when it's activated?
