### ISSUE TITLE
Enable two way synchronisation

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/ocsms#167]
At the moment, ocsms is just an one way sync.

Enable either two way sync or mention on Google Play Store as well as on Nextcloud App Store that this app is syncing only one way.

More info:
https://help.nextcloud.com/t/nextcloud-sms-1-11-4-one-way-or-two-way-sync/

**Comment by nerzhul** [comment]
Synchronization is fine, it doesn't mean two way sync, we have one way sync + restore messages support, it's similar to two way sync but not exactly, because restore can only be done manually

**Comment by enoch85** [comment]
@nerzhul You talked about implementing real 2 way sync in version 2.0. Restoring is not 2-way sync. 

2-way sync is: when you delete a message on the phone, it gets deleted in the app as well and vice versa.

**Comment by nerzhul** [comment]
@enoch85 yeah i know, v 2.0 is late because i manage many free software, that take some time :(

**Comment by enoch85** [comment]
@nerzhul You're the hero! :1st_place_medal:

**Comment by Richard-Payne** [comment]
Any progress on v2 @nerzhul?

**Comment by nerzhul** [comment]
not atm because i'm on other OSS projects, and i'm working on refactoring Android HTTP client code for recent SDKs

**Comment by shinenelson** [comment]
This issue can be closed in favor of one of the oldest open feature requests - #4
