### ISSUE TITLE
Messages with country code are split from messages without country code

### ISSUE THREAD

**Issue by Bodertz** [nextcloud/ocsms#171]
### Steps to reproduce
1. On phone, text yourself a message without using country code. You will receive the same message back.
2. On phone, text yourself a message using your country code. You will receive the same message.

Both messages you sent should be seen in the same conversation view.

3. Sync with server now.

### Expected behaviour
I should see one conversation on the server just as it is on the phone:

```
 +----------------------+
 |            Message 1 |
 | Message 1            |
 |            Message 2 |
 | Message 2            |
 |                      |
 | [              ] [>] |
 +----------------------+
 ```

### Actual behaviour

On server, there are two conversations.

### Server configuration

**NextCloud/ownCloud version:** 11.0.0

**PHP version:** 7.1.1

**HTTPd server:** apache

**HTTPS:**no

### Client configuration

**Android version:** 7.1.1

**Phone:** Moto E v2

**ownCloud SMS app version:** 0.24.1

**Comment by nerzhul** [comment]
duplicate #121
