### ISSUE TITLE
enable "don't remove from server"

### ISSUE THREAD

**Issue by lepidas** [nextcloud/ocsms#177]
This is a feature request.
I'd like to have the option not to "delete from server" global at least.
So I can keep my phone clean (deleting any message) but not the server.

**Comment by nerzhul** [comment]
what is the purpose ? Android app doesn't remove server messages, it push push incrementaly

**Comment by enoch85** [comment]
@lepidas There is no such thing as "2-way-sync", yet. As @nerzhul said, you can safley delete the messages on your phone without them getting deleted on the server. Closing, feel free to reopen if you think I'm wrong @lepidas
