### ISSUE TITLE
Undefined index when opening the Phone Sync app 

### ISSUE THREAD

**Issue by enoch85** [nextcloud/ocsms#178]
### Steps to reproduce
Never seen it before, but it happend when I opened the Phone Sync app in Nextcloud, which I haven't opened for like 2 months.

### Expected behaviour
No error output

### Actual behaviour
![screenshot from 2017-04-25 19-01-20](https://cloud.githubusercontent.com/assets/4511254/25397819/ffffce94-29e9-11e7-83b1-0132ed573c67.png)

### Server configuration

**NextCloud/ownCloud version:**
11.0.3
**PHP version:**
7.0
**HTTPd server:**
Apache 2.4
**HTTPS:**
Yes

### Logs

```
See Actual Behaviour --^ Also got this when I opened the app a second time:

Error	PHP	Undefined offset: 888 at /var/www/nextcloud/apps/ocsms/controller/smscontroller.php#229	2017-04-25T19:06:50+0200
```

**Comment by nerzhul** [comment]
Are you on stable or master?

**Comment by enoch85** [comment]
On stable.

**Comment by nerzhul** [comment]
Fixed, thanks
