### ISSUE TITLE
No synchro on my NextCloud :(

### ISSUE THREAD

**Issue by vincegre** [nextcloud/ocsms#182]
### Steps to reproduce
1. Installed app in my NextCloud (own instance) 11.0.3 (app version 1.11.5).
2. Installed the client (version 1.0.1) on my Oneplus 3 (Android 7.1.1).
3. Add my Nextcloud client in the app on mobile (I created a dedicated passwd for app as I use totp).
4. Try to synchronise and then I get the error on mobile: Erreur #9: Le serveur a renvoyé un code de retour HTTP non géré

### Expected behaviour
Tell us what should happen
Synchro should work silently

### Actual behaviour
Tell us what happens instead
Error message and that's it !

### Server configuration

**NextCloud/ownCloud version:**
11.0.3
**PHP version:**
7.0.15
**HTTPd server:**
Apache2
**HTTPS:**
Apache2
### Client configuration

**Android version:**
7.1.1
**Phone:**
OnePlus 3
**ownCloud SMS app version:**
1.0.1

**Comment by nerzhul** [comment]
Can you give us the HTTP code in your apache access logs ?

**Comment by vincegre** [comment]
Unhappy I already checked and didn't find anything relative to the app :( What is the begin of URL the app should generate on server ? so I can do a search on that in logs !
Might it be that the server is using a Let's Encrypt certificate ?

**Comment by 00tiagopolicarpo00** [comment]
Hi have the some erro on client side: 
Log server:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["username", "2017-05-08 14:36:11", "2017-05-08 14:36:11", "10", "1492704886000", 11828, "NumberPhone", "Multi SMS's", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x9E s...' for column 'sms_msg' at row 1

    /var/websites/www/localhost.local/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /var/websites/www/localhost.local/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO oc_...', Array)
    /var/websites/www/localhost.local/lib/private/legacy/db/statementwrapper.php - line 74: Doctrine\DBAL\Statement->execute(Array)
    /var/websites/www/localhost.local/apps/ocsms/db/smsmapper.php - line 289: OC_DB_StatementWrapper->execute(Array)
    /var/websites/www/localhost.local/apps/ocsms/controller/apicontroller.php - line 82: OCA\OcSms\Db\SmsMapper->writeToDB('tiagopolicarpo', Array)
    [internal function] OCA\OcSms\Controller\ApiController->push(11722, Array)
    /var/websites/www/localhost.local/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/websites/www/localhost.local/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\OcSms\Controller\ApiController), 'push')
    /var/websites/www/localhost.local/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\OcSms\Controller\ApiController), 'push')
    /var/websites/www/localhost.local/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ApiController', 'push', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/websites/www/localhost.local/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/websites/www/localhost.local/lib/base.php - line 1010: OC\Route\Router->match('/apps/ocsms/pus...')
    /var/websites/www/localhost.local/index.php - line 40: OC handleRequest()
    {main}

**Comment by nerzhul** [comment]
@00tiagopolicarpo00 please look at this https://github.com/nextcloud/ocsms#question-solve-encoding-errors-on-mysql

**Comment by vincegre** [comment]
Is it safe to do ? no risk to break the NextCloud itself ? and what about shared hosting ? consequences for other db on same MySQL server ?

**Comment by nerzhul** [comment]
it's safe and linked to database.

**Comment by 00tiagopolicarpo00** [comment]
Dear nerzhul,  now is working the sync. tks

**Comment by nerzhul** [comment]
no problem

**Comment by vincegre** [comment]
Here unable to modify the character_set of the nextcloud db and my poor mysql knowledges don't help :( it always complain about syntax error when I execute the line:
`ALTER DATABASE group CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
`
and I don't understand why :( Tried through the PHP interface I have in my control panel and directly in command line in mysql but no success !!

@00tiagopolicarpo00 did you get some issues with that part ?

**Comment by nerzhul** [comment]
@vincegre which database version do you have ? MySQL 5.5 or 5.6 is required for  this (or MariaDB 10.0)

**Comment by vincegre** [comment]
MySQL 5.7.18 here ;)

**Comment by 00tiagopolicarpo00** [comment]
You have a private server or a shared server?

**Comment by vincegre** [comment]
Well shared server but I'm the hoster ;)

**Comment by 00tiagopolicarpo00** [comment]
the Server variables and settings is enable?
innodb_large_prefix=on
innodb_file_format=barracuda
innodb_file_per_table=1

**Comment by nerzhul** [comment]
those variables have no functionnal impact on this app.

**Comment by vincegre** [comment]
@00tiagopolicarpo00 yeo I have done these changes already but the modifications on db itself and tables I have no luck :( My knowledges of MySQL are around zero but I tried to do the commands in command line at mysql prompt but syntax error all the time and same by doing it through the control panel that allows to send mysql requests directly !

**Comment by 00tiagopolicarpo00** [comment]
use phpmyadmin select the database and run on console.
ALTER DATABASE NAMEDATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
and Press Ctrl+Enter to execute query

**Comment by nerzhul** [comment]
no need for a ugly phpmyadmin, just go through SSH on your MYSQL server, enter mysql <dbname> and same request. phpmyadmin is a big security hole

**Comment by 00tiagopolicarpo00** [comment]
I dont use the phpmyadmin, but common on shared host with (ISP/Cpanel/Plesk) the phpmyadmin is install. 
When you connect to mysql have you using user with permissions?

**Comment by vincegre** [comment]
First I tried to do it easy way in the control panel I use (Virtualmin/Webmin) but complaining about a syntax error ! So I went the "hard" way, console on server, login to mysql as root user for it, and then made a select on the database and then made the command indicated replacing nextcloud by the name of my db but same result, error in your syntax so very confused where is the problem....

**Comment by 00tiagopolicarpo00** [comment]
Check end you copy and paste is good and the database name :
# mysql -u root -p 
ALTER DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;  (ENTER)
exit (ENTER)
Restart service:
# service mysql restart

**Comment by nerzhul** [comment]
An engine alter table doesn't require à service restart (hopefully)

**Comment by vincegre** [comment]
No copy/paste, everything typed by hand in terminal ! any ideas ?

`root@monhost:/root# mysql -u root -p                                              
Enter password:                                                                 
Welcome to the MySQL monitor.  Commands end with ; or \g.                       
Your MySQL connection id is 127023                                              
Server version: 5.7.18-0ubuntu0.16.04.1 (Ubuntu)                                
                                                                                
Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.    
                                                                                
Oracle is a registered trademark of Oracle Corporation and/or its               
affiliates. Other names may be trademarks of their respective                   
owners.                                                                         
                                                                                
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.  
                                                                                
mysql> ALTER DATABASE group CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;   
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that 
corresponds to your MySQL server version for the right syntax to use near 'group
 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci' at line 1                    
mysql>`

**Comment by nerzhul** [comment]
your database is called group ?

**Comment by brantje** [comment]
You're also having this issue with Passman (See: https://github.com/nextcloud/passman-android/issues/13 ).
So must be server related instead of app related.

**Comment by vincegre** [comment]
@nerzhul thanks the ` tip was the problem, problem solved ;)
@brantje no link between, OCSMS sync working fine on my cellphone since updated db schema :)
