### ISSUE TITLE
NC 12 error version in app store

### ISSUE THREAD

**Issue by Laupe** [nextcloud/ocsms#183]
Please correct app delivery to app store. NC 12 is not the latest version but older. Thank you

https://apps.nextcloud.com/apps/ocsms

![image](https://cloud.githubusercontent.com/assets/1008242/25872009/8a238b04-3509-11e7-96c5-d0ebe97779f6.png)

**Comment by nerzhul** [comment]
i think it's an old version with error. Irrelevant, will be closed. i will release a new version now

**Comment by nerzhul** [comment]
last version has been released
