### ISSUE TITLE
error sync :  Data too long for column 'sms_address' at row 1

### ISSUE THREAD

**Issue by neoguet** [nextcloud/ocsms#184]
### Steps to reproduce
1.
2.
3.

### Actual behaviour
When i launch the sync I've got an error #9 on the client (android).
The problem comes from the phone numbers I think

### Server configuration

**NextCloud/ownCloud version:**
Nextcloud 11.0.3 (stable)

**PHP version:**
PHP 7.1.4-1
**HTTPd server:**
Apache/2.4.18
**HTTPS:**
Yes
### Client configuration

**Android version:**
7.1.2
**Phone:**
One plus one (LineageOS 14.1)
**ownCloud SMS app version:**
1.0.1
### Logs

```
server log (phone numbers has been changed) : 
	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["neoguet", "2017-05-11 21:27:44", "2017-05-11 21:27:44", "11", "1483262921762", 8, "+33 6 77 77 77 17 +33 7 81 77 77 87 +33 6 70 77 67 70 +33 6 77 72 77 17 +33 7 76 77 78 77 +33 6 77 77 77 10 +33 6 77 06 77 78 +33 6 77 3477 77 +33 6 77 17 77 57", "bla bla", 1, 2]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'sms_address' at row 1
```

**Comment by nerzhul** [comment]
WoW !
Your phone number is very huge:
```
+33 6 77 77 77 17 +33 7 81 77 77 87 +33 6 70 77 67 70 +33 6 77 72 77 17 +33 7 76 77 78 77 +33 6 77 77 77 10 +33 6 77 06 77 78 +33 6 77 3477 77 +33 6 77 17 77 57```

I think your phone has a problem and sent a wrong phone number, it's not consistent. A problem in LineageOS ?

**Comment by nerzhul** [comment]
I'm closing this issue as server side problem is... logical here

**Comment by nerzhul** [comment]
Can you open an issue on the android application to let me check the android code ?

**Comment by neoguet** [comment]
hi
I've resolved my problem.
it's nor my number but numbers of recipients. First I can't retrieve this mesage on sms default app. After changing sms app, I deleted this message and sync is OK.

**Comment by nerzhul** [comment]
nice !
