### ISSUE TITLE
Cannot add an account on Android 6.0

### ISSUE THREAD

**Issue by fredscud** [nextcloud/ocsms#185]
Hi,
I have installed Nextclous SMS on my android 6.0 phone.
When I try to add an account using "Add an account" Nextcloud SMS menu, I can only add a Google Account.
I have no option to add a Nextcloud account. 
Do I have to set up something on my phone to allow the creation of a Nextcloud account for Nextcloud SMS ?
Thanks,
Fred.

Nextcloud SMS 1.0.1
Android 6.0.1
Archos 50f Helium

**Comment by nerzhul** [comment]
I'm on android 6.0 too on my work phone and the account type is there. only thing i can tell you is to reinstall, also, did you install from play store ?

**Comment by fredscud** [comment]
I was using the F-Droid version. I have just installed the Play Store version, but same problem.

**Comment by rosenrot** [comment]
F-Droid version 1.3.4 cannot add account. MIUI9 (android 6.0)
Error: "it's not web server"

**Comment by nerzhul** [comment]
Closing this issue
