### ISSUE TITLE
Deleted on phone but not in NextCloud !!

### ISSUE THREAD

**Issue by vincegre** [nextcloud/ocsms#186]
### Steps to reproduce
1. Delete an SMS thread on phone
2. Wait for synchronisation
3. Access OCSMS on Nextcloud and thread is still there

### Expected behaviour
Threads or SMS(s) deleted on phone should disappear in Nextcloud too

### Actual behaviour
Nothing the thread doesn't disappear in NextCloud

### Server configuration

**NextCloud/ownCloud version: 11.0.3

**PHP version: 7.0.15

**HTTPd server: Apache2

**Database engine & version: MySQL 5.7.18

### Client configuration

**Android version: 7.1.1

**Phone: OnePlus 3

**NextCloud SMS app version: 1.0.1

**Comment by nerzhul** [comment]
No it's not intended to work as is and i will generate heavy workload, this app is intended to offload your messages to nextcloud and remove it from your phone ;) sorry

**Comment by olantrust** [comment]
Absolutely agree with nerzhul. Users that sync to the cloud (for example photo apps, text message, emails) expect the cloud to preserve an archive history, a bigger set than the phone, unless they delete it on the cloud itself. Deleting on the cloud would be unexpected behaviour to most users and result in unexpected data loss.

**Comment by enoch85** [comment]
...Though it would be cool if 2-way sync was introduced together with the possibility to send messages directly from Nextcloud GUI. especially now when Hangouts is dropped.
