### ISSUE TITLE
SSL protocol support requires TLSv1?

### ISSUE THREAD

**Issue by db260179** [nextcloud/ocsms#188]
### Steps to reproduce
1.Turn off TLSv1 on nginx settings
2.Watch nginx error log - set to debug
3. Error 13 occurs, turn TLSv1 back on, connection works again.

### Expected behaviour
TLSv1.1 and 1.2 is considered to be safe, should not be forced to use TLSv1 or older protocols?

### Actual behaviour
SSL handshake refuses to connect

### Server configuration

**NextCloud/ownCloud version:**
8.2

**PHP version:**
5.7

**HTTPd server:**
nginx 1.6.2

**Database engine & version:** 
mysql 5.6

### Client configuration

**Android version:**
4.4

**Phone:**

**NextCloud SMS app version:**
latest

### Logs

```
 [info] 31963#31963: *11 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: x.x.x.xx.x, server: x.x.x.x.x:443
```

This error is a bit of a red herring as showing SSLv3, but same issue for TLSv1

**Comment by db260179** [comment]
This is a client issue, sorry please ignore this.

**Comment by nerzhul** [comment]
Hello,

your problem is related to your android version. On my Android 6 and my nginx TLS 1.2 is the only supported version and all works perfect
