### ISSUE TITLE
No examples of how to use the rest API for uploading sms texts.

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [nextcloud/ocsms#190]
The endpoint looks to be:

/apps/ocsms/push

But I'm unable to determine exactly what I need to post to this url to cause something to appear in the NC app, or if there are other endpoints that have to be hit first. Could you provide an example?

Attempting to load this from a jailbroken iphone via sqlite3/curl, but little success so far.

**Comment by nerzhul** [comment]
please look at smscontroller in the push endpoint you will se post param required
