### ISSUE TITLE
Error into log

### ISSUE THREAD

**Issue by azlux** [nextcloud/ocsms#193]
### Steps to reproduce
1. New install of nextcloud 12.0
2. Install OCSMS
3. watch log

### Actual behaviour
Everything is working fine. But I have 3 errors line into my nextcloud log:

`
Error | PHP | chmod(): Operation not permitted at /*****/*****/nextcloud/lib/private/Log/File.php#123 | 2017-07-16T12:39:55+0200
`
`
Error | PHP | Invalid argument supplied for foreach() at /*****/*****/nextcloud/apps/ocsms/db/smsmapper.php#264 | 2017-07-16T12:39:55+0200
`
`
Error | PHP | Invalid argument supplied for foreach() at /*****/*****/nextcloud/apps/ocsms/controller/apicontroller.php#112 | 2017-07-16T12:39:55+0200
`

I think the last 2 belong to ocsms. I can do more debug if needed !

### Server configuration

**NextCloud/ownCloud version:**
Nextcloud 12.0.0

**PHP version:**
7.0.21

**HTTPd server:**
nginx/1.10.3

**Database engine & version:** 
10.0.30-MariaDB

----
Thank
Az

**Comment by nerzhul** [comment]
thanks for the report, will look at this

**Comment by dmitryU** [comment]
I got the same error in Nextcloud SMS version 1.3, but the return to version 1.2.5 fixed the problem.
See https://github.com/nerzhul/ownCloud-SMS-App/issues/153

**Comment by nerzhul** [comment]
@dmitryU unrelated

**Comment by supermamie** [comment]
I have the same errors
Phone Sync 1.12.1
Nextcloud SMS 1.3.0
Nextcloud 12.0.3

I deleted those 2 received messages, from special numbers (I don't have them as contacts, but there is still a name displayed) and then, the synchronization worked again.

I have some messages from this kind of numbers that were synchronized, and I'm not sure that both of these cause crash (I deleted both of them as the same time)

![screenshot_20171110-231507](https://user-images.githubusercontent.com/693751/32680941-6a3373fe-c66d-11e7-90c4-664c55e87636.png)
![screenshot_20171110-231517](https://user-images.githubusercontent.com/693751/32680942-6a636b7c-c66d-11e7-8cbd-68e03f04f4c2.png)

**Comment by nerzhul** [comment]
Please upgrade to 1.3.1. deploy is in progress on play store since yesterday

**Comment by supermamie** [comment]
Just a note : I got the errors again today.
I'll wait for 1.3.1 on f-droid :-)

**Comment by supermamie** [comment]
I updated to 1.3.1 (from f-droid) and I now have these errors on the server : 


Level | App | Message | Time
-- | -- | -- | --
Error | PHP | Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85 | 2017-11-15T20:15:08+0100
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72 | 2017-11-15T20:15:08+0100
Error | PHP | call_user_func()  expects parameter 1 to be a valid callback, class 'OCA\OcSms\Db\Config'  not found at  /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php#318 | 2017-11-15T20:14:18+0100
Error | PHP | call_user_func()  expects parameter 1 to be a valid callback, class 'OCA\OcSms\Db\Config'  not found at  /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php#318 | 2017-11-15T20:14:17+0100
Error | PHP | call_user_func()  expects parameter 1 to be a valid callback, class 'OCA\OcSms\Db\Config'  not found at  /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php#318 | 2017-11-15T20:14:16+0100
Error | PHP | call_user_func()  expects parameter 1 to be a valid callback, class 'OCA\OcSms\Db\Config'  not found at  /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php#318 | 2017-11-15T20:14:10+0100

**Comment by nerzhul** [comment]
Update to 1.3.2 please

**Comment by supermamie** [comment]
1.3.2 is still not available on f-droid
https://f-droid.org/packages/fr.unix_experience.owncloud_sms/

**Comment by nerzhul** [comment]
as i said every time, i don't update those builds, just wait

**Comment by supermamie** [comment]
I'll wait, no problem, that was only the reason why I was still on 1.3.1 and not 1.3.2 :-)

**Comment by nerzhul** [comment]
@supermamie 1.3.4 did the trick, can you confirm ?

**Comment by supermamie** [comment]
I don't have error logs anymore (but no automatic save either, seems I have to do it manually)
(And I switched to the play store version, to avoid build delays ^^ )

**Comment by nerzhul** [comment]
Nice :)
