### ISSUE TITLE
Can't sync sms

### ISSUE THREAD

**Issue by dh-connect** [nextcloud/ocsms#198]
### Steps to reproduce
1. run sync on phone
2. no error on phone and no messages in nextcloud
3.

### Server configuration

**NextCloud/ownCloud version:**
12.0.2

**PHP version:**
PHP-Version: 7.0.19-1 

**HTTPd server:**
Apache/2.4.25 

**Database engine & version:** 
Server-Version: 10.1.23-MariaDB-9+deb9u1

### Client configuration

**Android version:**
7.1.2

**Phone:**
droid turbo

**NextCloud SMS app version:**
1.2.0

### Logs

found this error in apache error log, I'm using modsecurity
```
[:error] [pid 19846] [client xxx:42811] [client xxx] ModSecurity: JSON parsing error: lexical error: invalid character inside string.\n [hostname "xxx"] [uri "/owncloud/index.php/apps/ocsms/push"] [unique_id "xxx"]

```
found this error in nextcloud log
```
Invalid argument supplied for foreach() at /data/ownclouddata/www/owncloud/apps/ocsms/db/smsmapper.php#264

and

Invalid argument supplied for foreach() at /data/ownclouddata/www/owncloud/apps/ocsms/controller/apicontroller.php#112
```

**Comment by nerzhul** [comment]
hello,
tune your mod security. \n is used in SMS when you use multiline. It's not app related

**Comment by dh-connect** [comment]
I googled a bit, actually it's not a modsecurity problem, this error comes from json, because the linebreak is not propper escapped in the app. Please verify.

**Comment by nerzhul** [comment]
okay it's in the last version, can you re-open the issue on the android app repository ? https://github.com/nerzhul/ownCloud-SMS-App/issues
