### ISSUE TITLE
Unable to perform the HTTP connection

### ISSUE THREAD

**Issue by DBLouis** [nextcloud/ocsms#200]
LineageOS 14.1 (Android 7.1.2)
Nextcloud sms client 1.2.4
Nextcloud server 12

The app fails to connect to my nextcloud server. I get this error message :
_Unable to perform the HTTP connection. Make sure that this is an HTTP server_
My server use a certificate from my own CA, maybe this is related.

**Comment by nerzhul** [comment]
hello, can you give us logcat logs from android ?

**Comment by DBLouis** [comment]
```
[ ...  8582: 8582 I/fr.unix_experience.owncloud_sms.activities.LoginActivity.UserLoginTask ]
_serverURI = https://cloud.example.org

[ ...  8582:10774 I/fr.unix_experience.owncloud_sms.engine.OCHttpClient ]
Create GET https://cloud.example.org/index.php/apps/ocsms/get/apiversion?format=json

[ ...  8582:10774 W/fr.unix_experience.owncloud_sms.activities.LoginActivity.UserLoginTask ]
Failed to login, IOException occured: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

I would like to add that it works with other apps so the issue is not the server neither the phone.

**Comment by dmitryU** [comment]
I got the same error in Nextcloud SMS version 1.3, but the return to version 1.2.5 fixed the problem.
See https://github.com/nerzhul/ownCloud-SMS-App/issues/162

**Comment by nerzhul** [comment]
@dmitryU unrelated

**Comment by al-ign** [comment]
I have same problem (I suppose).
Moto E4 Gen 4
Nextcloud SMS 1.3.0 from F-Droid
Android 7.1.1
Nextcloud 11.0.4 (stable)
I have 2T PKI, both certificates installed on the phone, Nextcloud App from F-droid, DAV Droid and in browser I can access server without certificate warnings.
Can't provide logcat, don't have root on this phone.

**Comment by nerzhul** [comment]
Please upgrade to 1.3.1

**Comment by DBLouis** [comment]
There is no 1.3.1 on F-Droid

**Comment by nerzhul** [comment]
There is on play store, i don't know who maintain the f-droid port

**Comment by snapet** [comment]
Upgrade to 1.3.1 did not solve this for me.
Android 4.4.4
Samsung S4 mini
Nextcloud 12.0.3

**Comment by nerzhul** [comment]
@DBLouis is this solved ?

**Comment by nerzhul** [comment]
it seems the remaining notification is on the full sync periodic processus, i will look at this

**Comment by nerzhul** [comment]
Okay i found a second issue, and it's only in the periodic sync in some cases. It's now fixed and 1.3.2 has been published to play store

**Comment by hackitz** [comment]
I still have this issue, latest version of nextcloud, android 8. Latest version of nextcloud sms 132.

**Comment by nerzhul** [comment]
can you give us logs and post your issue on https://github.com/nerzhul/ownCloud-SMS-App
