### ISSUE TITLE
Misleading feedback when login fails

### ISSUE THREAD

**Issue by Korodny** [nextcloud/ocsms#202]
_Edit: Please ignore this - after one (?) successful sync, I now get the same error message again ("Unknown HTTP response code"). I didn't notice that earlier, because the phone was freshly installed and there were simply no SMS to sync. I'll investigate further and report back_

After I installed and configured Nextcloud SMS, I got notifications about the sync process failing due to an "Unknown HTTP response code".

I was about to start logging the whole process, but decided to simply reenter my credentials in case I had a typo in the password. Now syncing works fine - so I assume the problem was indeed a typo.

Unfortunately, I can't post my Apache logs yet (just some rented webspace, today's logs will only be available tomorrow), but I know from older login problems with Nextcloud that it usually returns a 401 status code when login fails for some reason.

That status code shouldn't be reported as an "unknown response code", but as a login problem.

**Comment by nerzhul** [comment]
Thanks for the return
