### ISSUE TITLE
New Setup - MySQL Errors

### ISSUE THREAD

**Issue by ckibodeaux** [nextcloud/ocsms#203]
### Steps to reproduce
1. Working stable version of Nextcloud 12
2. Install Phone Sync app into Nextcloud
3. Purchase, install and setup Nextcloud SMS
4. Press synchronize on the phone app

### Expected behaviour
SMS should sync over to Nextcloud

### Actual behaviour
I get a sync successful message, but nothing is showing up in Nextcloud. Log shows multiple errors.

### Server configuration

NextCloud/ownCloud version: 12.0.3

PHP version: 7.0

HTTPd server: Apache2 2.4.18

Database engine & version: MySQL 5.7.19

### Client configuration

Android version: 8.0.0 with Security Patch October 5, 2017

Phone: Google Pixel 1

NextCloud SMS app version: 1.2.4

### Logs

```
Error	index	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["ckibodeaux", "2017-10-16 00:49:39", "2017-10-16 00:49:39", "11", 1495935412263, 7177, "+12254139347", "\ud83d\ude21Not funny!!", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\xA1No...' for column 'sms_msg' at row 1
```

**Comment by nerzhul** [comment]
Hello
please look at this part of the README: https://github.com/nextcloud/ocsms#question-solve-encoding-errors-on-mysql

It's an encoding problem on your database, ty to MySQL.

**Comment by ckibodeaux** [comment]
Thanks! Like a dummy, I missed the readme when searching.

**Comment by ckibodeaux** [comment]
OK. I've followed the steps, but I'm still not having luck.

1. Set InnoDB properties in MySQL config.
2. Change Character set.
mysql> ALTER DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
> Query OK, 1 row affected (0.00 sec)
3. Set config.php
> /var/www/nextcloud$` sudo -u www-data ./occ config:system:set mysql.utf8mb4 --type boolean --value="true"
System config value mysql.utf8mb4 set to boolean true
4. Run maintenance:repair
> /var/www/nextcloud$ sudo -u www-data ./occ maintenance:repair
 - Repair MySQL collation
     - Change row format for oc_accounts ...
     - Change collation for oc_accounts ...
     - Change row format for oc_activity ...
     - Change collation for oc_activity ...

  [Doctrine\DBAL\Exception\DriverException]                                                                                                                                                                                      
  An exception occurred while executing 'ALTER TABLE `oc_activity` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':                                                                                                       
  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change   
  some columns to TEXT or BLOBs                                                                                                                                                                                                  

  [Doctrine\DBAL\Driver\PDOException]                                                                                                                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change   
  some columns to TEXT or BLOBs                                                                                                                                                                                                  

  [PDOException]                                                                                                                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change   
  some columns to TEXT or BLOBs
