### ISSUE TITLE
Unable to link to existing NextCloud account on Android

### ISSUE THREAD

**Issue by Richard-Payne** [nextcloud/ocsms#205]
### Steps to reproduce
1. install Nextcloud SMS
2. Load app
3. Add Account
4. Select NextCloud from the account list
5. Input server address
6. Authenticate

### Expected behaviour
Nextcloud SMS links to the existing account

### Actual behaviour
Receive an error saying that an account for that server and user already exists.

### Server configuration

NextCloud/ownCloud version: NC12.0.3

PHP version: 7.0.22

HTTPd server: Apache 2.4.18

Database engine & version: MySQL 10.2.9 MariaDB

### Client configuration

Android version: 7.0

Phone: Samsung Galaxy S6

NextCloud SMS app version: 1.2.4

### Logs

Not sure which logs you want.

**Comment by Richard-Payne** [comment]
Nevermind, I understand it now.  You need to select the "NextCloud SMS" account type.  This seems a like confusing to me since NextCloud already has an account on my phone.  Is not possible to simply link to that instead of requiring me to input my credentials again?

**Comment by nerzhul** [comment]
hi @Richard-Payne there was a discussion at a point but i don't have any information about that or using the account properly
