### ISSUE TITLE
Unable to perform a HTTP connection

### ISSUE THREAD

**Issue by loi219** [nextcloud/ocsms#207]
When I'm adding an account in the app, I can't connect it with the server.
I've an error: Unable to perform a HTTP connection Please ensure there is a web server
But the application on nextcloud is installed and I can access the server with my phone

### Steps to reproduce
1. Add account
2. Fill url, username, password

### Expected behaviour
Connect with server

### Actual behaviour
Unable to perform a HTTP connection Please ensure there is a web server

### Server configuration

**NextCloud/ownCloud version: ** 12.0.3

**PHP version: ** 5.6.30

**HTTPd server: ** Apache/2.4.25

**Database engine & version:** MySQL 5.5.57

### Client configuration

**Android version:** 6.0

**Phone:** Huawei P8-Lite

**NextCloud SMS app version:** 1.3.0

### Logs
No logs

P.S thanks for what you're doing

**Comment by dom134** [comment]
Hello, I also have this problem.  The app did work with a previous phone, but not any more.
Nextcloud.log:

> {"reqId":"tThvEGLEeWVJBgsD42yT","level":2,"time":"2017-11-15T20:36:03+00:00","remoteAddr":"86.0.111.11","user":"--","app":"core","method":"POST","url":"\/nextcloud\/index.php\/apps\/ocsms\/get\/apiversion?format=json","message":"Trusted domain error. \"86.0.111.11\" tried to access using \"mywebsite.com\" as host.","userAgent":"nextcloud-phonesync (1.3.1)","version":"12.0.3.3"}
> 
> {"reqId":"JJw8djgCkSUwwFvOyBvY","level":3,"time":"2017-11-15T20:58:47+00:00","remoteAddr":"86.0.111.11","user":"--","app":"index","method":"POST","url":"\/nextcloud\/\/index.php\/apps\/ocsms\/get\/apiversion?format=json","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/nextcloud\\\/index.php\\\/apps\\\/ocsms\\\/get\\\/apiversion) cannot be processed by the script '\\\/nextcloud\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(956): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":729}","userAgent":"nextcloud-phonesync (1.3.1)","version":"12.0.3.3"}
> 
> {"reqId":"NXORaVlPNoSh7qWEUVJE","level":3,"time":"2017-11-15T20:59:05+00:00","remoteAddr":"86.0.111.11","user":"--","app":"index","method":"POST","url":"\/nextcloud\/\/index.php\/apps\/ocsms\/get\/apiversion?format=json","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/nextcloud\\\/index.php\\\/apps\\\/ocsms\\\/get\\\/apiversion) cannot be processed by the script '\\\/nextcloud\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php(751): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(794): OC\\\\AppFramework\\\\Http\\\\Request->getPathInfo()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1086): OC::init()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/index.php(46): require_once('\\\/var\\\/www\\\/nextcl...')\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":729}","userAgent":"nextcloud-phonesync (1.3.1)","version":"12.0.3.3"}

**Server configuration**

**NextCloud/ownCloud version:** 12.0.3.3

**PHP version:** 7.0.22

**HTTPd server:** Apache/2.4.18

**Database engine & version:** MySQL 5.7.20


**Client configuration**

**Android version:** 7.1.2

**Phone:** Meizu Pro 5

**NextCloud SMS app version:** 1.3.1

**Comment by pierfu** [comment]
Hi,
same behaviour here since a few weeks, same error message.

**Comment by OrpheeGT** [comment]
Same happens for me.
I reverted back to 1.2.5 on F-droid and it works again.

**Comment by dom134** [comment]
Thanks @OrpheeGT, that works again.  There must be something in the 1.3.0 and 1.3.1 versions...

**Comment by nerzhul** [comment]
The 1.3.2 version fix the @dom134 problems mentioned in your server logs, there were a problem in /api/version call in periodic sync passed as a POST instead of GET

**Comment by nerzhul** [comment]
And sorry for the problems in that refactors, some tests were not concluant in my dev environment, but it's okay now

**Comment by OrpheeGT** [comment]
@nerzhul thank you, waiting for it on F-droid.

**Comment by loi219** [comment]
@nerzhul thanks
