### ISSUE TITLE
Cannot create Nextcloud SMS account with working server (HTTP error)

### ISSUE THREAD

**Issue by ColinMaudry** [nextcloud/ocsms#208]
### Steps to reproduce
1. Install Nextcloud SMS from F-Droid
2. Try to create a new Nextcloud SMS sync account
3. Enter [chez.colin.ovh](https://chez.colin.ovh) in the URL field, with HTTPS selected
4. Enter some credentials
5. Click on SIGN IN

### Expected behaviour

The account should be created.

### Actual behaviour

Error on the URL field: 

Unable to perform a HTTP connection. Please ensure there is a Web server.

### Server configuration

**NextCloud/ownCloud version:** NC 12.0.2

**PHP version:** 7.0.19 CLI

**HTTPd server:** nginx reverse proxy

**Database engine & version:** MySQL 5.5

### Client configuration

**Android version:** 6.0.1 (Fairphone Open)

**Phone:** Fairphone 2

**NextCloud SMS app version:** 1.3.1 (installed via F-Droid)

### Logs

I don't know how to get logs for this app.

**Comment by Philippe-M** [comment]
I've a identical problem with NextClound 12.0.3 and 2 phone's Android 6.0 and Android 6.0.1

**Comment by nerzhul** [comment]
1.3.2 is requirecd, but it seems i missed a push + tag push on github then the code is not updated on F-Droid, but it's released on Google play store

**Comment by ColinMaudry** [comment]
I don't use the Play Store, and F-Droid still shows no update after a source update.

The issue is consequently not solved unless the update is published on F-Droid.

**Comment by nerzhul** [comment]
as i said 1.3.2 is the solution but it's not published yet and i don't maintain this build, but i will push the missing informations on github this weekend and F-Droid should update at a point

**Comment by bperel** [comment]
I have this problem as well, using version 1.3.3.

Worth noting that my NextCloud instance is not located at the root of the host, as the screenshot shows:

![screenshot_20171219-195222](https://user-images.githubusercontent.com/1484692/34173718-b4882358-e4f6-11e7-8c55-b205adadd32d.png)
