### ISSUE TITLE
SMS not syncing due to incorrect string value

### ISSUE THREAD

**Issue by xiphias256** [nextcloud/ocsms#210]
It seems that some of my sms are encoded in a way that the sync software doesn't like. It then blocks the app to complete its sync. All sms that shows up in the error-logs from Nextcloud, seems to contain some sort of smileys/emoji. 

### Steps to reproduce
1. Install app in Nextcloud
2. Install Nextcloud SMS app on phone
3. Configure phone app and start syncing sms

### Expected behaviour
I should get all sms from phone into nextcloud

### Actual behaviour
I got 3  phonenumbers of the last sms received. Most of the contacts is without it's name, but phone number instead.

### Server configuration

**NextCloud/ownCloud version:**
12.0.3

**PHP version:**
7.0.22

**HTTPd server:**
Apache 2.4.18

**Database engine & version:** 
MySQL 5.7.20

### Client configuration

**Android version:**
Android 6.0.1
**Phone:**
Sony Z3 compact

**NextCloud SMS app version:**
1.3.2
### Logs

Apache gives an 500 error on POST
"POST /index.php/apps/ocsms/push?format=json HTTP/1.1" 500 10975 "-" "nextcloud-phonesync (1.3.2)"

In Nextcloud I get multipe messages with "incorrect string value", like this:

Error | index | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas  (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address,  sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with  params ["username", "2017-12-01 20:28:55", "2017-12-01 20:28:55", "10",  1500549989000, 4411, "+XXXXXXXX", "Done \ud83d\ude09", 0, 1]:  SQLSTATE[HY000]: General error: 1366 Incorrect string value:  '\xF0\x9F\x98\x89' for column 'sms_msg' at row 1
-- | -- | --

**Comment by nerzhul** [comment]
Hello, it's due to your MySQL configuration.
See https://github.com/nextcloud/ocsms#question-solve-encoding-errors-on-mysql

Thanks
