### ISSUE TITLE
Nextcloud 13 support

### ISSUE THREAD

**Issue by psottek** [nextcloud/ocsms#213]
Is it correct that ocsms 1.10.1 support nextcloud 13?

**Comment by nerzhul** [comment]
currently max-version is set to 12 but i will update the max-version after release to verify this

**Comment by prilly** [comment]
nextcloud 13 beta 3 is out, and i would like to test this app on this version, nice if you could bump the max-version.

**Comment by grogg** [comment]
1.10.1 is not supporting Nextcloud 13.  Even with the max version bumped up the following error is present when attempting to enable the app:

An exception occurred while executing 'ALTER TABLE oc_ocsms_smsdatas CHANGE `sms_msg` `sms_msg` VARCHAR(20480) NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'sms_msg' (max = 16383); use BLOB or TEXT instead

**Comment by pounard** [comment]
I just changed the max version to 13 manually in the app info xml file, and it worked fine (using 1.12.1 version).

**Comment by nerzhul** [comment]
Release done with max version bumped
