### ISSUE TITLE
No Entries in DB / No error shown

### ISSUE THREAD

**Issue by Kalle73kw** [nextcloud/ocsms#216]
### Steps to reproduce
1. Install Phonesync Addon
2. Install Android App
3. Try to sync
4. No error shown

### Expected behaviour
Showing error message on android app or in logs on server 
or 
Having some data in "oc_ocsms_smsdatas"- table

### Actual behaviour
Neither the one or the other 

### Server configuration

**Nextcloud/ownCloud version:**
Nextcloud 12.0.4
Phonesync 1.12.2

**PHP version:**
7.0.8

**HTTPd server:**
Apache 2.2 

**Database engine & version:** 
MySQL 5.1.73

### Client configuration

**Android version:**
7.0

**Phone:**
Galaxy S8

**Nextcloud SMS app version:**
1.3.4

### Logs

no log entries

**Comment by Kalle73kw** [comment]
I de- and reinstalled the server and the android app several times now. Also resetted the sync-cursor.  No difference. Are there any files anywhere i have to delete for complete reset and start from the beginning? Or maybe its a temporary workaround to sync to aother instance and ex-/import the DB?

**Comment by chainsawbike** [comment]
i am having the same issue, could it be this apache bug?

https://bz.apache.org/bugzilla/show_bug.cgi?id=53332

**Comment by nerzhul** [comment]
Hello @Kalle73kw first, if you can upgrade MySQL from 5.1 to 5.6 or 5.7, or use MariaDB 10.0 at least you will prevent having UTF8MB4 issues, can you first do that ?

**Comment by Kalle73kw** [comment]
Hey! I'm on hosted server, so I don't have rights to do installations or upgrades, but I can set up a testing enviroment with Maria 10.1. I tell you as soon as I'm ready with it!

**Comment by Kalle73kw** [comment]
So, now I'm on a server with

PHP 7.1.13
Maria Version: 10.1.30
nextcloud 13.0.0
Phonesync 1.12.2

App Version is 1.3.4 

and what should I say... IT'S WORKING AGAIN! ;) 
So, first of all, the the bug is not on the Android side...

**Comment by nerzhul** [comment]
nice to head, thanks for your report.
