### ISSUE TITLE
Problem connecting nextcloud server and phone app

### ISSUE THREAD

**Issue by JunkyardCat** [nextcloud/ocsms#217]
Hi

I need help on how to setup an account. I have nextcloud on my raspberry pi only available locally
when logging into nextcloud i usually type in ip address 192.XXX.X.XXX. im able to synch this with davdroid and nextcloud app fine but not sure why nextcloud sms app is having trouble.

i have both nextcloud sms on the nextcloud server and the app android phone. I install phone sync app on the nextcloud server. Is that the same as what you said or is ocsms server app a different app?

Steps to reproduce

    open nextcloud sms
    click on add an account
    choose nextcloud sms
    type in 192.XXX.X.XXX/ (using https option but i didnt write https in the field)
    enter admin
    enter password for admin
    click sign in

Expected behaviour

Nextcloud admin account will be added

Actual behaviour

error in the server address field.
Unable to perform a http connection. please ensure there is a web server
Server configuration

Nextcloud version:
12
PHP version:

**Comment by nerzhul** [comment]
did you select the correct protocol (HTTP vs HTTPS)

**Comment by JunkyardCat** [comment]
My server uses https and i selected from the dropdown https on my mobile app.

**Comment by jean-gui** [comment]
I believe I have the same issue, except that my server is available from Internet. I get the same error when trying to connect from the Android app. HTTPS is properly selected and I use a device password.

Server logs excerpt:
```
xxx.xxx.xxx.xxx - user [26/Jan/2018:14:41:22 +0100] "POST //index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 405 4758 "-" "nextcloud-phonesync (1.3.0)"
```

If I change the verb from GET to POST for routes 'api#get_api_version' and 'api#retrieve_all_ids' in ocsms/appinfo/routes.php, the app will successfully log in and start synchronizing. I am not yet 100% sure that synchronization does indeed work as I don't see my latest SMS in the web ui.

**Comment by nerzhul** [comment]
your version is outdated, please use 1.3.4 , 1.3.0 to 1.3.3 has connnectivity issues

**Comment by jean-gui** [comment]
Indeed. I'm not sure why Play Store did not update it automatically. I had to reinstall it. Perhaps I had previously installed it by some other means, I can't recall.
I also reinstalled the extension in Nextcloud and dropped the tables otherwise nothing was synchronizing.

**Comment by nicolass67** [comment]
Hello, 

I have same problem and already opened issues, but still not better. [https://github.com/nerzhul/ownCloud-SMS-App/issues/153] 
From a 2-3 months discuss with the developper it could be a problem with the routing of request/json in nextcloud. 

I just updated Nextcloud to 12.0.5. with ocsms 1.12.2  => Not better 
Server is Debian stretch + nginx + php7.0-fpm. 
Android client 1.3.4 is up to date

I recently tried too : 
- disable gzipping in nginx => Fail 
- switch php-fpm to inet mode instead of socker mode => fail 

What I found strange is that in logs you get a 200 when posting the SMS : 
`POST /index.php/apps/ocsms/push?format=json HTTP/1.1" 200 54 "-" "nextcloud-phonesync`
But nothing appears in the DB for sms datas :
` sqlite3 owncloud.db .dump | grep -i sms => NOTHING (unless table and index creation) `

Regards,

**Comment by nerzhul** [comment]
@nicolass67 did you use standard android SMS app ?

**Comment by nicolass67** [comment]
@nerzhul : Yes Nexcloud SMS from Play store (I buyed it ) latest version. Already tried desinstall / reinstall with cache and data purge when desinstalling it

**Comment by JunkyardCat** [comment]
@nerzhul i am already using 1.3.4. I installed from the F-Droid repo though

**Comment by nicolass67** [comment]
Hello all, 

This morning I tried something to see if it is server side or client side. 
My previous configuration was : 
nginx -> php-fpm -> nextcloud => SMS not syncing 
I just tried this configuration : 
nginx -> proxy all request to local apache => apache2 with php 7.0 module (not fpm) -> nextcloud => SMS synced. 

Something must so be screwed in the php-fpm or in the fastcgi handling. Maybe someone here will have knowledge of a parameter in php-fpm that could make this ? 

Regards,

**Comment by nerzhul** [comment]
hi @nicolass67 your return is very interesting, do you have PHP logs in FPM ? maybe some things cannot be send to FPM. FPM is a PHP app server and you use proxy_pass on your nginx to send things over HTTP to it, right ?

**Comment by nicolass67** [comment]
OK it really seems the problem comes from PHP-FPM/fastcgi

- Working configuration : 
nginx -> proxy all request to local apache => apache2 with php 7.0 module (not fpm) -> nextcloud 

- Not working configuration : 
nginx -> proxy all request to local apache => apache2 with php-fpm -> nexcloud

I googled a little but I didn't find any answer. 
What is for me more annoying is that I use a lot of nextcloud apps, all work like a charm with php-fpm. 

My knowledge quite stops here , but if anyone reading this has advanced skills to debug I can help to test. 

Regards,

**Comment by al-ign** [comment]
You definitely should enable php-fpm logs and look there.
They are enabled somehow like this: 

> php-fpm.conf

```
[global]
error_log = /var/log/php-fpm/fpm-error.log

[www]
access.log = /var/log/php-fpm/access.log 
```

**Comment by nicolass67** [comment]
@al-ign : 
I tried already. Only get running infos (even with log_level= debug ) : 
When ocsms comes with his request : 
`DEBUG: pid 31575, fpm_children_make(), line 421: [pool wwwinet] child 31654 started`
access_log : 
`127.0.0.1 - nico 30/Jan/2018:16:09:20 +0100 "POST /index.php" 200`

Again it's strange it gets a 200 but nothing happens behind. 

Nothing in nginx logs even with 
fastcgi_intercept_errors on ; and proxy_intercept_errors on;

**Comment by JunkyardCat** [comment]
@nerzhul

Do you happen to know how to fix my problem?

**Comment by nicolass67** [comment]
I managed to find out what was wrong. 
In the nextcloud documentation in the block location : 
`location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {`
an option is used : 
`fastcgi_request_buffering off;` 

Comment this line, restart Nginx , sync your SMSes -> OK
Uncomment this line, restart Nginx, generate new SMS -> Not synced 
Comment again the line, restart Nginx , sync your SMS -> OK
So this option causes OCSMS not to sync ... I dont know why and why other apps work with the option, but this is a workaround. 

@nerzhul : maybe you can check with nexcloud team

**Comment by nerzhul** [comment]
@nextcloud/infrastructure are you aware of this nginx issue in the default configuration ?

**Comment by MorrisJobke** [comment]
cc @josh4trunks

**Comment by josh4trunks** [comment]
I am not sure when/why `fastcgi_request_buffering off;`  was added to the owncloud/nextcloud docs. It looks like it can help with underpowered systems with low cache/disk-space. This has never been relevant to my personal setups and I have never used this.

I think it would be good to remove this parameter. It is already documented here https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_files/big_file_upload_configuration.rst#nginx

**Comment by nerzhul** [comment]
All comments on the issue has been answered. We will try to enhance the user experience in future release. The major rework has been done with NC 14
