### ISSUE TITLE
SMS not synchronised when default app is the default messaging app in Android

### ISSUE THREAD

**Issue by loi219** [nextcloud/ocsms#219]
### Steps to reproduce
1. Connect to the account

### Expected behaviour
SMS synchornised with the server

### Actual behaviour
I'm not using the default messaging app in Android, but Silence. The synchronisation goes well when the default messaging app is the default app for SMS but not when it's Silence.

### Server configuration

**Nextcloud/ownCloud version:**

**PHP version:**

**HTTPd server:**

**Database engine & version:**MySQL 5.6.14**
### Client configuration

**Android version:**8.1**

**Phone:*Xiaomi Redmi note 4*

**Nextcloud SMS app version:*1.12.2*

### Logs

```
No log
```

**Comment by nerzhul** [comment]
Duplicate issue on android app repository.
This is not related to server app
