### ISSUE TITLE
Self Signed SSL Certificates are refused and no option to accept

### ISSUE THREAD

**Issue by aewhite901** [nextcloud/ocsms#221]
### Steps to reproduce
1. Create a self signed ssl cert
2. Install into server
3. Attempt to add an account

### Expected behaviour
Should have let me login
### Actual behaviour
I am unable to login with the error mesage

Low Level error: get https://web.addr.ess/nextcloud/nextcloud-------
json:x509:certificate valid for "Xdomain" not "Y domain"

All other apps run with NextCloud and have no issue with self signed cert.

### Server configuration
N/A
**Nextcloud/ownCloud version:**
12.0.4
**PHP version:**

**HTTPd server:**

**Database engine & version:** 

### Client configuration

**Android version:**

**Phone:**

**Nextcloud SMS app version:**
2.0.3
### Logs

```
Insert your log here
```

**Comment by nerzhul** [comment]
Hello @aewhite901 
you are on the wrong repository, it's the repository for the server here.
your error means your self signed certificate doesn't allow the web.addr.ess hostname, please create a self signed with the right domain name

**Comment by aewhite901** [comment]
Strange that every other application works with the certificate yet the SMS app does not.
I can login and use https://web.addr.ess/nextcloud  without issue.

**Comment by nerzhul** [comment]
i understand, but the problem is the certificate domain name is not matching the used domain name

**Comment by aewhite901** [comment]
So what? Why does your app not allow me to accept the certificate?
My email client allows it in fact other NextCloud apps and even NextCloud
is fine with it.

**Comment by aewhite901** [comment]
Can you add an allow option for the certificate instead of simply refusing to accept it?

**Comment by nerzhul** [comment]
in fact it's already allowed, but the golang SSL implementation is a little bit stricter than the java lazy implementation

**Comment by aewhite901** [comment]
then noone with any ssl certificate that does not match will not be able to match correct?
It means we cannot use your app therefore we cannot use NextCloud as well. Shame
really it had such great promise.
