### ISSUE TITLE
The first line of SMS is hidden by the headband

### ISSUE THREAD

**Issue by PatriceLorant** [nextcloud/ocsms#223]
Hi Loïc,
I like the development of your applications. It's a very good job.
In Nextcloud, in the "Phon Sync SMS" window, I can not view the first line of SMS.
She is hidden by the headband :
+3399999999
9 message (s) shown. 9 message (s) stored in database.

Too bad;
Best regards.
Patrice

**Comment by nerzhul** [comment]
It's now fixed since the vue.js migration
