### ISSUE TITLE
Nextcloud 14 - drop of deprecated APIs

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ocsms#224]
Hi just want to inform you that with 14 we will drop for example `linkTo*` methods of `OCP\Util` nextcloud/server#8811

See the PHPDoc in that class for how to handle this now.

Please also have a look at nextcloud/server#7827 for other dropped methods or use the app:code-check to highlight deprecated methods in the current code.

**Comment by nerzhul** [comment]
Not used here

**Comment by MorrisJobke** [comment]
It is used in here - otherwise I would not have opened it ;)

For example here:
https://github.com/nextcloud/ocsms/blob/master/appinfo/app.php#L24

**Comment by nerzhul** [comment]
Fixed
