### ISSUE TITLE
Nextcloud 14 will drop OCP\DB support

### ISSUE THREAD

**Issue by rullzer** [nextcloud/ocsms#226]
Hi, OCP\DB is deprecated since version 8.1 and will run into the 3 year deprecation time soon. With the upcoming Nextcloud 14 this will not be available anymore. We highly encourage you to move over from to the \OCP\IDBConnection. Preferably even to the IQueryBuilder. If you need help with the migration please reach out to us.

The removal PR: https://github.com/nextcloud/server/pull/8985

**Comment by nerzhul** [comment]
If you have a PR i take it :)

**Comment by MorrisJobke** [comment]
Also ref https://github.com/nextcloud/server/issues/7827

**Comment by jospoortvliet** [comment]
Perhaps useful example: https://github.com/e-alfred/ocdownloader/pull/74

**Comment by nerzhul** [comment]
Hello @rullzer @MorrisJobke 
I started the migration but i don't find how to perform a limit on the query in NC 13. I need that in some code paths

https://github.com/nextcloud/ocsms/commit/8a0580e7c42906d74846e15b124c6a78cce9406b

**Comment by MorrisJobke** [comment]
> I started the migration but i don't find how to perform a limit on the query in NC 13. I need that in some code paths
> 
> 8a0580e
> 
> If you can help

It's called `setMaxResults`: 

https://github.com/nextcloud/server/blob/0009358c17b4c84d94efc94ed91d097d11e4321a/lib/public/DB/QueryBuilder/IQueryBuilder.php#L265-L273

**Comment by nerzhul** [comment]
Solved
