### ISSUE TITLE
SMS Connect to owncloud

### ISSUE THREAD

**Issue by ken948** [nextcloud/ocsms#231]
### Steps to reproduce
1.https://owncloud.<server>
2.<user id>
3.<password>

### Expected behaviour
create account 
### Actual behaviour
Tell us what happens instead
Tell us what should happen
Error message:
"Low level error:Get https://owncloud.<domain>/index.php/apps/ocsms/get/apiversion?format=json:x509:certificate signed by unknown authority"

### Server configuration

**Nextcloud/ownCloud version:**
ownCloud	10.0.7 (stable)
**PHP version:**
PHP 7.0.29
**HTTPd server:**
httpd 2.4.6
**Database engine & version:** 
mysql Ver 14.14 Distrib 5.6.40
### Client configuration

**Android version:**
7.1.1
**Phone:**
Nexus 6
**Nextcloud SMS app version:**

### Logs

```
Insert your log here
```

**Comment by nerzhul** [comment]
Hello, ensure the certificate chain is proper

**Comment by ken948** [comment]
What does it mean.  Can you provide an example?  There is no issue with the remote client access app. on my Android

**Comment by nerzhul** [comment]
Yeah it's because it uses the java certificate chain which is less strict than the golang chain

**Comment by ken948** [comment]
Okay, you gave an explanation on why it doesn't work. How do I get around it?
