### ISSUE TITLE
Reset Database Option

### ISSUE THREAD

**Issue by sootstone** [nextcloud/ocsms#233]
### Steps to reproduce
1. Go to ocsms web interface of Nexctcloud/ownCloud instance.
2. Attempt to reset database / clear all messages (start from scratch).
3.

### Expected behaviour
Option to reset database in settings, thus clearing all messages.

### Actual behaviour
Messages are deleted individually.

**Comment by dthrash** [comment]
Not sure where your seeing a setting to clear all the messages. You can delete entire conversations with individuals. If you're wanting to delete all conversations you could delete all rows within the  oc_ocsms_smsdatas table.

**Comment by nerzhul** [comment]
@dthrash but if you do that you will do for all users. Idea can be cleanup per user. I can add a wipe button somewhere

**Comment by nerzhul** [comment]
Please note you can drop the whole contact data, not only individual messages

**Comment by nerzhul** [comment]
Feature is now in master

![capture d ecran de 2018-09-08 11-41-24](https://user-images.githubusercontent.com/119752/45252735-2aba0f80-b35c-11e8-825b-d0e439f5a38d.png)
