### ISSUE TITLE
SMS not synching and not displaying

### ISSUE THREAD

**Issue by schniepp** [nextcloud/ocsms#236]
### Steps to reproduce
1. Install android app and correctly setup access credentials.
2. Install ocsms app on NC
3. Click on ocsms app in NC

### Expected behaviour
The synched SMS should show up.
The database should be populated with SMS messages, metadata, etc.

### Actual behaviour
The screen just remains totally plain; no SMS or any specific information showing up. 
Inspecting some of the table with phpmyadmin, they are all empty. It appears that nothing was synched. On the phone it looks like the sync was successful.

### Server configuration
ubuntu 18.04
**Nextcloud/ownCloud version:** NC 13.0.0.4

**PHP version:**
7.1

**HTTPd server:**
apache

**Database engine & version:** 
mySQL 5.7.22

### Client configuration
ubuntu 16.04, chrome

**Android version:**

**Phone:**
LG G6

**Nextcloud SMS app version:**
1.12.7

### Logs
There were quite a few errors of this format in the server log:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["*****", "2018-05-17 12:51:17", "2018-05-17 12:51:17", "11", 1516924452852, 87, "+1**********", "\ud83d\udc4d", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x91\x8D' for column 'sms_msg' at row 1
```
(Asterisks were introduced to mask personal information.)
Does the error indicate that there were illegal string characters? Could this be an issue related to the employed character set?

**Comment by nerzhul** [comment]
Hello
just read the readme.md

https://github.com/nextcloud/ocsms#question-solve-encoding-errors-on-mysql
