### ISSUE TITLE
Already read messages don´t sync with server

### ISSUE THREAD

**Issue by enoch85** [nextcloud/ocsms#24]
### Steps to reproduce
1. Get a SMS on your phone
2. Read it
3. Go to server
4. Message is unread.

This should be synced, but I guess that comes with the 2-way sync in 2.0?

**Comment by enoch85** [comment]
Any update here @nerzhul ? :)

**Comment by nerzhul** [comment]
@enoch85 not at this moment, sorry, i was designing and thinking about restoring messages. I don't have thought about a method to check if messages are read or not. Maybe in the global sync check the unread messages on server and compare with client :)

**Comment by enoch85** [comment]
Looking forward to 2-way sync. :) Any update?

**Comment by shinenelson** [comment]
I believe two-way sync (#4) has been one of the oldest open feature request. This issue can be closed in favor of that one.
