### ISSUE TITLE
No information about API

### ISSUE THREAD

**Issue by MRZA-MRZA** [nextcloud/ocsms#240]
I didn't find API reference so I looked into code and found some info:

There are two API versions. I checked that my nextCloud ocsms installation supports both of them. Should I only one API?

I played with it and managed to add a message but I don't have a clue what mbox, type, read and seen parameters are. How do I know which id I should use?

**Comment by nerzhul** [comment]
hello, the API is not really described. I should enhance it later, but current i have some frontend rework & android app rework to do

**Comment by nerzhul** [comment]
Hello,
i started to document API there:

https://github.com/nextcloud/ocsms/blob/master/doc/swagger.yml
