### ISSUE TITLE
How import all sms and not only from ocsms apk installation?

### ISSUE THREAD

**Issue by danjde** [nextcloud/ocsms#243]
Hi Staff and thanks for your wonderful work!
Then, I would like to know if is it possible to synchronize not only the "last messages" (after apk installation and configuration) but all messages, previous the apk date install.

Many many thanks!

Davide

**Comment by danjde** [comment]
Hi @nerzhul and very thanks for your help!
I've done as you suggest me and now all works fine! All messages have been synchronized!

Another question if possible: using ocsms is it possible to import/synchronize sms from Nextcloud to a new (blank) phone?

Many many thanks again!

Davide
Italy

**Comment by nerzhul** [comment]
you will have in the same app menu restore messages option to fetch all SMS from server.
Thanks for your report
