### ISSUE TITLE
Phonesync shows new unread messages counter but shows no SMS in the conversation pane

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/ocsms#260]
### Steps to reproduce
1. Sync new SMS from Android to Nextcloud using Phonesync 1.13.1
2. Open latest messages indicated on left pane with the bold text indicating unread messages.

### Expected behaviour
All messages including old ones should be shown in the right conversation pane.

### Actual behaviour
No messages are shown on the right pane, only "Please choose a conversation on the left menu". Old read messages aren't shown either.

### Server configuration

**Nextcloud/ownCloud version:** 13.0.4

**PHP version:** 7.0

**HTTPd server:** Apache 2.4

**Database engine & version:**  Mariadb 10

### Client configuration

**Android version:** Android 7.1.1

**Phone:** BQ X5 Plus

**Nextcloud SMS app version:** 2.0.4

**Comment by nerzhul** [comment]
should be fixed by 5bbb1292c859519e5f529a945b676fd66236a5ee
