### ISSUE TITLE
Rename app to reflect its functionality

### ISSUE THREAD

**Issue by Larx** [nextcloud/ocsms#263]
Please rename the app to something more fitting.
In fact, from the name "phone sync" the average user nowadays expects a (very much!) wider range of functions (files, pictures, instant messenger, remote location etc.). However, Phone sync does only one thing, it syncs SMS messages. So I propose to rename the app to "SMS Sync" or something like that, not to raise wrong expectations!

**Comment by nerzhul** [comment]
at the beginning there was owncloud SMS, then phone sync, because when i get time i will have phone call sync too, but not files, because there is an app for this.
