### ISSUE TITLE
Git signing key 0XD1FCA204F1ADF6ED60B9D651EFAA458E8C153987 not found on major key servers

### ISSUE THREAD

**Issue by yan12125** [nextcloud/ocsms#272]
### Steps to reproduce
1. `git verify-commit 1.13.1`
```
gpg: Signature made Thu Jun 28 23:05:07 2018 CST
gpg:                using RSA key D1FCA204F1ADF6ED60B9D651EFAA458E8C153987
gpg: Can't check signature: No public key
```
2. Try to search key 0xD1FCA204F1ADF6ED60B9D651EFAA458E8C153987 on major key servers. I've tried pgp.mit.edu and keyserver.ubuntu.com

### Expected behaviour
I can verify git commits & tags

### Actual behaviour
Nothing can be verified due to missing public key

**Comment by nerzhul** [comment]
maybe i didn't publish it on public servers, i just use it on GH and Gitlab without publishing it

**Comment by yan12125** [comment]
Seems the key is not correctly configured on GitHub, either? The commit for
1.13.1 is marked as "Unverified":
https://github.com/nextcloud/ocsms/commit/bac897df2c9b475a86d34113eede0c0cfc8aee67

Loïc Blot <notifications@github.com> 於 2018年9月20日 週四 下午3:27寫道：

**Comment by nerzhul** [comment]
Yeah i did it from another computer, without the key at this moment, i know some are very attached to a such quality, but sometimes i'm lazy about the signing issue :)

I ensure you it's the correct release

**Comment by yan12125** [comment]
> i know some are very attached to a such quality

Like me :D

> I ensure you it's the correct release

Thanks! It would be still great to be able to validate future releases automatically.

**Comment by yan12125** [comment]
Finally I managed to reconstruct a public key from a GitHub API and use that to verify git commits. I posted details at https://blog.chyen.cc/posts/2019/08/29/github-api-gpg-public-key.html.
