### ISSUE TITLE
After upgrading to NextCloudPi 14.0.1 no more SMS displayed

### ISSUE THREAD

**Issue by elbarbudo** [nextcloud/ocsms#276]
### Steps to reproduce
1. NextCloudPi 13 installed and running
2. OCMS installed and running : lots of SMS
3. Automatic upgrade to NextCloudPi 14.0.1
4. Connect to my account and try to get SMS

### Expected behaviour
Have my sms displayed

### Actual behaviour
Waiting and nothing displayed
![capture du 2018-10-10 08-36-50](https://user-images.githubusercontent.com/2513291/46717401-140f1d00-cc68-11e8-8987-c2c02007a4bf.png)

### Server configuration

**Nextcloud/ownCloud version:**  NextCloudPi 14.0.1

**PHP version:** 
PHP 7.2.9-1 (cli) (built: Aug 19 2018 06:56:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9-1, Copyright (c) 1999-2018, by Zend Technologies

**HTTPd server:** Apache2 2.4.25-3+deb9u5

**Database engine & version:** 
mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

### Client configuration

**Android version:**

**Phone:**

**Nextcloud SMS app version:**

### Logs

```
Insert your log here
```

**Comment by Flore-mozfr** [comment]
Hello,

I have exactly the same issue. Not on a Pi, but on a webserver. It worked with NC13.x and does not display any SMS after automatic upgrade to 14.01

**Comment by 9R** [comment]
The cause is probably the issue described in #266 and #226. Since that has been fixed hopefully the next release includes the fix and SMS should be displayed again.
If you can not or do not want to wait until then you can try your luck with installing the app from git or downgrade back to nc13 (keep in mind  that an already upgraded db is probably incompatible so use a backup).

**Comment by elbarbudo** [comment]
I just installed 14.02 and there was NO correction.

**Comment by 9R** [comment]
@elbarbudo sorry I did not make that clear in my previous comment: A new release of the sms-app is needed. New nextcloud releases will not fix this issue.
