### ISSUE TITLE
2.1.0 not retrieving data on NCP 14.04

### ISSUE THREAD

**Issue by LsPjvVzszDt** [nextcloud/ocsms#284]
### Steps to reproduce
1. Update Phone Sync to 2.1.0
2. Select Phone Sync from browser

### Expected behaviour
Rendering of page on Browser

### Actual behaviour
Page does not populate any data

### Server configuration
Nextcloud Pi

**Nextcloud/ownCloud version:**
14.0.4

**PHP version:**
PHP 7.2.13

**HTTPd server:**
Apache/2.4.25

**Database engine & version:** 

### Client configuration

**Android version:**

**Phone:**

**Nextcloud SMS app version:**

### Logs

```
Insert your log here
```

Settings do not appear to be read:

![screenshot from 2018-12-17 11-29-43](https://user-images.githubusercontent.com/30001047/50084506-202ad400-01ef-11e9-90a9-435ef10dd82a.png)

**Comment by nerzhul** [comment]
Hello
thanks for your report. Can you give me your browser logs ?

**Comment by LsPjvVzszDt** [comment]
Chromium and Firefox logs:

file:///home/alan/Desktop/firefox.log


file:///home/alan/Desktop/chromium.log

**Comment by LsPjvVzszDt** [comment]
[firefox.log](https://github.com/nextcloud/ocsms/files/2686632/firefox.log)
[chromium.log](https://github.com/nextcloud/ocsms/files/2686635/chromium.log)

**Comment by nerzhul** [comment]
@LsPjvVzszDt :

```
(index):1 Refused to execute script from 'https://cloud.brighthead.uk/index.php/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

It seems your server is badly configured in terms of MIME types. It's not a issue with this application which only uses standard nextcloud API

**Comment by LsPjvVzszDt** [comment]
The server uses a stock Nextcloud Pi image. 
So the issue shows an incompatibility with the Nextcloud Pi build?

**Comment by nerzhul** [comment]
It seems a header is set and blocks the JS loading in the firefox logs

**Comment by LsPjvVzszDt** [comment]
Both Firefox and Chromium run Ublock Origin and Firefox runs uMatrix. With these disabled the result is the same.

2.0.2 was running OK and the issue was only after upgrade to 2.1.0

**Comment by nerzhul** [comment]
Okay

**Comment by gpgmailencrypt** [comment]
Same here on LinuxMint  Tara and Firefox. Version 2.0.2 was working without any problem.

**Comment by schniepp** [comment]
Same here. Server is running nc 14.0.3.
OCSMS 2.0.2 worked as expected. Upgrade to 2.1.0 completely broke functionality. My backup server still has 2.0.2 and is working. 
Strangely, I cannot downgrade to 2.0.2. When I manually install the zip with 2.0.2, it triggers a repair of NC, which automatically updates OCSMS back to 2.1.0. Now, I can't even downgrade! Does the 2.1.0 upgrade do any database changes that cannot be reverted?

**Comment by nerzhul** [comment]
@schniepp no there is no special schema upgrade in 2.1 it's cosmetic only.

**Comment by schniepp** [comment]
Thanks! I will see if there is a way around it.

**Comment by schniepp** [comment]
In case someone is interested: I had to disable and remove the app, then use "'has_internet_connection' => false," and "  'updatechecker' => false," in config.php. Then reload the nextcloud instance in the browser. Strangely, in the APPS manager, I still had to click on "disable" for the app once again. 
Then, I was able to install v2.0.2 again, and the old entries show up as they used to.

**Comment by e-alfred** [comment]
I have the same problem with 2.1.0 on Nextcloud 14.0.4 on Ubuntu 18.04. It worked well before the update. I attached the log from the console. The problem happens in all browsers.

```
VM347:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=bbc4e587-1:3877)
    at Object.register (merged-template-prepend.js?v=bbc4e587-1:3829)
    at de.js?v=bbc4e587-1:1
_generatePluralFunction @ merged-template-prepend.js?v=bbc4e587-1:3877
register @ merged-template-prepend.js?v=bbc4e587-1:3829
(anonymous) @ de.js?v=bbc4e587-1:1
VM350:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=bbc4e587-1:3877)
    at Object.register (merged-template-prepend.js?v=bbc4e587-1:3829)
    at de.js?v=bbc4e587-1:1
_generatePluralFunction @ merged-template-prepend.js?v=bbc4e587-1:3877
register @ merged-template-prepend.js?v=bbc4e587-1:3829
(anonymous) @ de.js?v=bbc4e587-1:1
VM353:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=bbc4e587-1:3877)
    at Object.register (merged-template-prepend.js?v=bbc4e587-1:3829)
    at de.js?v=bbc4e587-1:1
_generatePluralFunction @ merged-template-prepend.js?v=bbc4e587-1:3877
register @ merged-template-prepend.js?v=bbc4e587-1:3829
(anonymous) @ de.js?v=bbc4e587-1:1
6Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
toolbarContentscript.js:122 {message: "The message port closed before a response was received."}
```

**Comment by e-alfred** [comment]
@nerzhul I also got these errors in the nextcloud.log file which means you forgot to remove developer mode from this commit: https://github.com/nextcloud/ocsms/commit/8c289e09de26dbca0549d03ef9c127e7a7d032b0

I reverted the changes and 2.1.0 works perfectly.

```
{"reqId":"XBwSS6RG3Hl@T-OS2pX19AAAAC4","level":0,"time":"2018-12-20T23:06:03+01:00","remoteAddr":"83.215.44.12","user":"alfred","app":"ocsms","method":"GET","url":"\/owncloud\/apps\/ocsms\/","message":"Could not find resource file \"\/owncloud\/apps\/ocsms\/js\/devel\/app.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.85 Safari\/537.36 Vivaldi\/2.2.1388.34","version":"14.0.4.2"}
{"reqId":"XBwSS6RG3Hl@T-OS2pX19AAAAC4","level":0,"time":"2018-12-20T23:06:03+01:00","remoteAddr":"83.215.44.12","user":"alfred","app":"ocsms","method":"GET","url":"\/owncloud\/apps\/ocsms\/","message":"Could not find resource file \"\/owncloud\/apps\/ocsms\/js\/devel\/settings.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.85 Safari\/537.36 Vivaldi\/2.2.1388.34","version":"14.0.4.2"}
{"reqId":"XBwSS6RG3Hl@T-OS2pX19AAAAC4","level":0,"time":"2018-12-20T23:06:03+01:00","remoteAddr":"83.215.44.12","user":"alfred","app":"ocsms","method":"GET","url":"\/owncloud\/apps\/ocsms\/","message":"Could not find resource file \"\/owncloud\/apps\/ocsms\/js\/devel\/contactlist.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.85 Safari\/537.36 Vivaldi\/2.2.1388.34","version":"14.0.4.2"}
{"reqId":"XBwSS6RG3Hl@T-OS2pX19AAAAC4","level":0,"time":"2018-12-20T23:06:03+01:00","remoteAddr":"83.215.44.12","user":"alfred","app":"ocsms","method":"GET","url":"\/owncloud\/apps\/ocsms\/","message":"Could not find resource file \"\/owncloud\/apps\/ocsms\/js\/devel\/conversation.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.85 Safari\/537.36 Vivaldi\/2.2.1388.34","version":"14.0.4.2"}
{"reqId":"XBwSS6RG3Hl@T-OS2pX19AAAAC4","level":0,"time":"2018-12-20T23:06:03+01:00","remoteAddr":"83.215.44.12","user":"alfred","app":"ocsms","method":"GET","url":"\/owncloud\/apps\/ocsms\/","message":"Could not find resource file \"\/owncloud\/apps\/ocsms\/js\/devel\/helpers.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.85 Safari\/537.36 Vivaldi\/2.2.1388.34","version":"14.0.4.2"}
{"reqId":"XBwSS6RG3Hl@T-OS2pX19AAAAC4","level":0,"time":"2018-12-20T23:06:03+01:00","remoteAddr":"83.215.44.12","user":"alfred","app":"ocsms","method":"GET","url":"\/owncloud\/apps\/ocsms\/","message":"Could not find resource file \"\/owncloud\/apps\/ocsms\/js\/devel\/notifications.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.85 Safari\/537.36 Vivaldi\/2.2.1388.34","version":"14.0.4.2"}
```

**Comment by nerzhul** [comment]
Do you mean reverting the dev mode return back fixes the problem (using the minified version as it should be ?)

If yes i will repackage app :)

**Comment by e-alfred** [comment]
Yes, reverting to production mode solves the issue.

**Comment by nerzhul** [comment]
@e-alfred can you try the 2.1.1 release and tell me if it's okay in your environment ?
https://github.com/nextcloud/ocsms/releases/download/2.1.1/ocsms-2.1.1.tar.gz

**Comment by schniepp** [comment]
I tried it, and it looks better, but not yet working. 

The left side (contact list) now successfully shows up. 
However, the main part of the page still shows a spinner and never loads. Now, I am this error: 
```
Uncaught ReferenceError: twemoji is not defined
    at Object.<anonymous> (app.min.js?v=3d5519c0-22:1)
    at Function.each (core.js?v=3d5519c0-22:2)
    at hn.formatConversation (app.min.js?v=3d5519c0-22:1)
    at Object.success (app.min.js?v=3d5519c0-22:1)
    at j (core.js?v=3d5519c0-22:2)
    at Object.fireWith [as resolveWith] (core.js?v=3d5519c0-22:2)
    at x (core.js?v=3d5519c0-22:4)
    at XMLHttpRequest.<anonymous> (core.js?v=3d5519c0-22:4)
```

**Comment by nerzhul** [comment]
Oh i forgot to update the release script to include twemoji, my bad

**Comment by e-alfred** [comment]
Well, only those lines should be commented out:

```
//\OCP\Util::addScript('ocsms', 'devel/app');
//\OCP\Util::addScript('ocsms', 'devel/settings');
//\OCP\Util::addScript('ocsms', 'devel/contactlist');
//\OCP\Util::addScript('ocsms', 'devel/conversation');
//\OCP\Util::addScript('ocsms', 'devel/helpers');
//\OCP\Util::addScript('ocsms', 'devel/notifications');
```

**Comment by nerzhul** [comment]
Yes ! new package uploaded: https://github.com/nextcloud/ocsms/releases/download/2.1.1/ocsms-2.1.1.tar.gz it should just run fine.
After this release i will try to have a better JS packaging process with gulp

**Comment by nerzhul** [comment]
Solved . 2.1.1 will be published to appstore
