### ISSUE TITLE
How can we backup from one server and restore onto another ?

### ISSUE THREAD

**Issue by poofyteddy** [nextcloud/ocsms#286]
Hello,
I'm in the middle of a migration, and i was wondering what was the correct way to migrate oscms data.
The issue i'm facing is that i can't just dump and load the mysql database, the future instance won't have the same user name, nor id ...
I have browsed the db structure, and sadly my sql skill are way to low for me to try guessing how to import data by hand.
Would they be a way to backup sms data per user, and load them on another server afterward ?
can i just change the user_id from oc_ocsms_smsdatas and load it like that ?
Thank's for your time and effort in your project !

**Comment by nerzhul** [comment]
Hello @poofyteddy yes, you can dump the table & restore + fix the user_id, that will do the trick.

**Comment by poofyteddy** [comment]
Worked very well. Thank for the info.
