### ISSUE TITLE
Please make a new release supporting Nextcloud 16

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/ocsms#293]
Currently only version 1.10 is showing up as a version compatible with Nextcloud 16, which seems to be very outdated (because for 14 and 15 the app is already at 2.1.1). Please push a new release of the latest app version to the App Store that supports Nextcloud 16 .

**Comment by smirkybg** [comment]
NC 16 is now in stable. Any chance of updating Phone Sync (ocsms) soon to catch-up?

**Comment by e-alfred** [comment]
@nerzhul Are you still maintaining this app? Or are you searching a new maintainer for Ocsms too?

**Comment by ShapeShifter499** [comment]
Is there anything specific that needs updating for NC 16?  Or can the app run as normal?

**Comment by ShapeShifter499** [comment]
I just upgraded from NC 15 to NC 16 and because I already had the app installed before the upgrade I had 2.1.1 installed.  I was able to get that version working by re-enabling it with the ""Activate unstable app" option from the admin account's 'apps' page.

**Comment by e-alfred** [comment]
@nerzhul Are you looking for a new maintainer for this app too? Also the Android app is not available anymore on the Play Store.

**Comment by ShapeShifter499** [comment]
@e-alfred I think this is maybe because of Google's new SMS policy? https://www.androidpolice.com/2019/01/05/googles-new-sms-and-call-permission-policy-is-crippling-apps-used-by-millions/

@nerzhul if this is the case and you cannot get Google to allow the app. You should update this repository to let people know that the app is on F-Droid.    

https://f-droid.org/packages/fr.unix_experience.owncloud_sms/
https://github.com/nerzhul/ncsms-android

**Comment by e-alfred** [comment]
Yes, this crackdown is probably also part of the removal. But Google also has the same feature now (called "Messages for Web") which this app provided already years before (except for sending). There is a link to F-Droid already on the Github page, maybe a link to the app should be put in the Nextcloud app directly (in the settings pane) to notify users it is available on F-Droid.

**Comment by nerzhul** [comment]
yeah thanks google crap for play store. I battle 3 times, 3 times the fucking bot said no you are not firstly a SMS application. I stopped to battle.

**Comment by e-alfred** [comment]
@nerzhul I fixed the info.xml file for a new release: https://github.com/nextcloud/ocsms/commit/f8c0cb985c889daa3ffe3c8c0db0a6a770a7f25c

The Google Play Store problem is definitely bad. I think we should add a link to the settings menu (and the screen showing up before a client is set up) to the repository, F-Droid and the latest APK file itself. Not as convenient, but better than nothing.

**Comment by e-alfred** [comment]
@nerzhul The app should be fixed, can you push a new release?

**Comment by nerzhul** [comment]
I will try. At first there is a packaging issue

```
Release version set to 2.1.3
npm WARN ocsms No repository field.
npm WARN ocsms No license field.

audited 1209 packages in 1.982s
found 6 vulnerabilities (1 low, 1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/home/nerzhul/Devel/PHP/ocsms/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/nerzhul/Devel/PHP/ocsms/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/nerzhul/Devel/PHP/ocsms/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by nerzhul** [comment]
I'm unable to push the release currently

**Comment by e-alfred** [comment]
@nerzhul Their infrastructure is still a bit broken, somewhere I saw that they are looking for a system administrator or so. How often does the CI pick up a new release and push it to apps.nextcloud.org after creating a new release on Github?

**Comment by e-alfred** [comment]
@nerzhul The app store seems to work again, can you push a new release to the App Store for both the Weather app and OCSMS?

**Comment by LsPjvVzszDt** [comment]
@nerzhul Could I check to see if you've pushed your app updates yet please?

**Comment by nerzhul** [comment]
2.1.3 published on the app store. Sorry for the delay
