### ISSUE TITLE
Last ocsms update breaks nextcloud installation by altering table

### ISSUE THREAD

**Issue by Neurozone** [nextcloud/ocsms#294]
### Steps to reproduce
1. ALTER TABLE oc_ocsms_user_datas CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
2. update nextcloud
3. bam !

### Expected behaviour
Nexcloud should update correctly

### Actual behaviour
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_ocsms_smsdatas` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;': SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x8A' for column `cloud`.`oc_ocsms_smsdatas`.`sms_msg` at row 63

### Server configuration

**Nextcloud/ownCloud version:** last one

**PHP version:** 7.3

**HTTPd server:**

**Database engine & version:**MariaDB 10.3

### Client configuration

**Android version:**

**Phone:**

**Nextcloud SMS app version:**

### Logs
Your last alter table breaks my nexclooud update by trying an alter on a table i'm already altered with real unicode support (see utf8mb4)
I want to disable the alter when updating nexcloud !

**Comment by Neurozone** [comment]
In fact, to gain real unicode support in mysql you should have:
oc_ocsms_smsdatas | CREATE TABLE `oc_ocsms_smsdatas` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `added` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `lastmodified` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `sms_id` bigint(20) NOT NULL,
  `sms_address` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sms_msg` varchar(10240) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sms_date` bigint(20) NOT NULL,
  `sms_flags` varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '00',
  `sms_mailbox` smallint(6) NOT NULL,
  `sms_type` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `smsdata_user_mailbox` (`user_id`,`sms_mailbox`),
  KEY `smsdata_user_smsid` (`user_id`,`sms_id`),
  KEY `smsdata_user_mailbox_date` (`user_id`,`sms_mailbox`,`sms_date`),
  KEY `smsdata_user_mailbox_address` (`user_id`,`sms_mailbox`,`sms_address`),
  KEY `smsdata_user_mailbox_address_date` (`user_id`,`sms_mailbox`,`sms_address`,`sms_date`),
  KEY `idx_ocsms_smsdata1` (`sms_address`,`sms_date`,`sms_mailbox`,`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=34034 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC |


I'm a DBA...

**Comment by nerzhul** [comment]
i agree with you but we are working with doctrine generic interface to push scheme to both mysql and postgresql. And yes mysql utf8 is shit

**Comment by Neurozone** [comment]
Problem solved by adding:
 'mysql.utf8mb4' => true,
in config.php of NextCloud installation

NextCloud when updating will change the collation of all tables and installation goes just fine
