### ISSUE TITLE
App not found

### ISSUE THREAD

**Issue by kierenblack** [nextcloud/ocsms#295]
### Steps to reproduce
1. Click on link to app in playstore

### Expected behaviour
I am guessing it should take me to the app

### Actual behaviour
App not found

**Comment by e-alfred** [comment]
Can you tell us where exactly you found the broken link? Maybe with a screenshot?

**Comment by BornToBeRoot** [comment]
![image](https://user-images.githubusercontent.com/16019165/58800191-81acf680-8607-11e9-991e-52d4ed025213.png)

and 

![image](https://user-images.githubusercontent.com/16019165/58800204-8b365e80-8607-11e9-9ce6-66a3c3c435f2.png)

**Comment by e-alfred** [comment]
Okay, that is the Android App, not the Nextcloud App. The app got removed by Google because of their new policies: https://github.com/nextcloud/ocsms/issues/293#issuecomment-494087231

@nerzhul Can you remove the link to the Play Store in the Android app repository?

**Comment by redtux** [comment]
Hi everybody! :wave: 

JFYI, the dead link is still there.

* https://play.google.com/store/apps/details?id=fr.unix_experience.owncloud_sms

Is this one the correct link?

* https://f-droid.org/packages/fr.unix_experience.owncloud_sms/

The last release uploaded to F-Droid is v2.0.5 from 2018-12-23.

Is this the latest release of the Android app? Will the app also be supported on Android 9?

Thank you for your help and for this very useful app! :+1:

**Comment by e-alfred** [comment]
Where did you find the dead link? I removed it from both repositories, if there is still one left, please tell me where (at least in the Github repositories). 

The F-Droid link is correct and the app works pretty well on the latest Lineageos 16/Android 9. Maybe @nerzhul can fix the app if there are any issues with newer Android releases.

**Comment by redtux** [comment]
Ah, cool! Could you change the description on F-Droid? It says "Application is fully compatible from Android 4.0 to 8.0". Just checked: In the repo's README there is the right link, but it needs to be changed (or removed) in the description here on GitHub (which is not part of the git repo). Mea culpa, as I clicked there first… 🙂

**Comment by e-alfred** [comment]
That is only something @nerzhul can do.

**Comment by nerzhul** [comment]
hello, this app is a little bit over as google removed it and i miss time to develop it and fix things.
i may do some cleanups to improve the app but i don't know when yet
