### ISSUE TITLE
NC 17 incompabitility

### ISSUE THREAD

**Issue by schniepp** [nextcloud/ocsms#301]
After upgrading to NC 17, this app was disabled. It only has the option "Enable untested app" — but I don't want to break anything, so I have not yet tested that.

**Comment by e-alfred** [comment]
@nerzhul Can you create a new release of OCSMS and the Weather app and publish them to the Nextcloud app store?

**Comment by nerzhul** [comment]
@e-alfred noted, i can do it

**Comment by nerzhul** [comment]
release done, sorry for the delay

**Comment by nerzhul** [comment]
Hmmm no it failed to upload on the nextcloud store

```
info.xml contains malformed xml: XML declaration allowed only at the start of the document, line 1, column 7 (<string>, line 1)
```

**Comment by e-alfred** [comment]
@nerzhul I fixed it in https://github.com/nextcloud/ocsms/commit/ff0c890f0b8888f80aca426c2aeef0af25097685, it should work now.

**Comment by nerzhul** [comment]
Release done, sorry for the delay. Don't forget you can generate a release yourself then i just need to perform the signature :)

**Comment by ShapeShifter499** [comment]
Has this been fixed yet?

**Comment by ShapeShifter499** [comment]
Sorry, after some updates I have gotten the updated ocsms and it appears to work ok on Nextcloud 17
