### ISSUE TITLE
NC 18 incompability

### ISSUE THREAD

**Issue by Klemens2** [nextcloud/ocsms#307]
App is getting deactivated when updating to NC18...

Thanks in advance
```

**Comment by e-alfred** [comment]
Can you try to activate it as an untested app and see if any errors come up and check if sync works?

**Comment by samuraiii** [comment]
Hi,
I have tried this but it is not working.
What do you need to know from me to help you?
S

**Comment by samuraiii** [comment]
There seem to be some info in logs reagerding ocsms:
`{"reqId":"XXXXX","level":3,"time":"2020-01-29T12:37:31+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"user","app":"no app in context","method":"POST","url":"/nextcloud/index.php/settings/apps/enable","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"ocsms.sms.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php","line":339,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["ocsms.sms.index",[],1]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/Route/CachingRouter.php","line":59,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["ocsms.sms.index",[],false]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/URLGenerator.php","line":82,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["ocsms.sms.index",[]]},{"file":"/var/www/localhost/htdocs/nextcloud/apps/ocsms/appinfo/app.php","line":24,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["ocsms.sms.index"]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/legacy/app.php","line":266,"args":["/var/www/localhost/htdocs/nextcloud/apps/ocsms/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":["ocsms"]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/legacy/app.php","line":966,"function":"loadApp","class":"OC_App","type":"::","args":["ocsms"]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/Installer.php","line":154,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["ocsms",{"step":"OCA\\OcSms\\Migration\\FixConversationReadStates"}]},{"file":"/var/www/localhost/htdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":443,"function":"installApp","class":"OC\\Installer","type":"->","args":["ocsms"]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["ocsms"],[]]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/localhost/htdocs/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/localhost/htdocs/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/localhost/htdocs/nextcloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}`

**Comment by e-alfred** [comment]
This is strange. Initially, I had the same issue you posted come up in my logs, but after I removed the app from the /app directory and reinstalled it through the app store it works well now. Maybe you could try to remove it from the /app folder and reinstall it from the app store?

**Comment by samuraiii** [comment]
I removed the app from apps folder on NC installation and reinstalled it throug appstore. I have "reset all mesages" in NC and "reinitialized cursor" in oscms android app. 
The messages sync but I can see only "the other side" in coversation. I cant see my messages.
If the numbed by contact name is number of messages, than it shows right count but when you click on the thred you see only "the other side".

**Comment by Klemens2** [comment]
Sorry, at the moment I have not really time to test it. And as I am a real beginner in setting up nextcloud,  I assume there will be more qualified users for testing  ocsms.

**Comment by Klemens2** [comment]
Sorry for closing this, was a mistake

**Comment by nerzhul** [comment]
version published o the store

**Comment by samuraiii** [comment]
Thank you
