### ISSUE TITLE
l10n: Add plural to string

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/ocsms#318]
https://github.com/nextcloud/ocsms/blob/06eee652c4e979e1a1808ee4731768da083d0d8b/templates/main.php#L121

Reported at Transifex.

**Comment by e-alfred** [comment]
Fixed by https://github.com/nextcloud/ocsms/commit/5391cd9c3f67ca6da517f8dc885b53171a657832. Thanks for your help!
