### ISSUE TITLE
Update on Nextcloud Apps

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/ocsms#327]
Thanks for the update @e-alfred !
May I ask you to bring the update also on https://apps.nextcloud.com/apps/ocsms ? I don’t know how it works, maybe you already requested it ? 

Thanks

**Comment by e-alfred** [comment]
@nerzhul has to upload it to the App Store. I am just waiting for him.

**Comment by nerzhul** [comment]
hello, sorry for the delay, @e-alfred didn't i gave you the keys ?

**Comment by nerzhul** [comment]
i just published it
