### ISSUE TITLE
No branches available for translations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/ocsms#345]
@e-alfred @nerzhul what is the state of the app.
We recently fixed our transifex setup so it correctly sends emails on errors and it seems this app here is affected.
There is no master, stable23, stable22 or stable21 branch to get the translations from and to.

Is this app still active/maintained or should we remove the translation syncing for the time being?

**Comment by nerzhul** [comment]
hello,
it's pretty strange that the master branch disappear. As original owner of the app i never commited since many time. I don't know what happened

**Comment by nerzhul** [comment]
i pushed an old master branch i have on my computer. Let's try to find more historical data now

**Comment by nerzhul** [comment]
ok i restored until the 22nd september 2021, i have no more, i think transifex can fix the remaining no @nickvergessen ?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/ocsms/commit/5479e663475a894827a6015fae8e697090fee4ae

Works again, yes. Thanks for the fast help
